// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO app_audit_logs (
  id, category, subcategory, event_type, action, outcome,
  actor_user_id, actor_organization_id, target_type, target_id, target_display,
  request_id, trace_id, span_id, ip_address, user_agent,
  metadata_json, changes_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type InsertAuditLogParams struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	Category            string             `db:"category" json:"category"`
	Subcategory         string             `db:"subcategory" json:"subcategory"`
	EventType           string             `db:"event_type" json:"event_type"`
	Action              string             `db:"action" json:"action"`
	Outcome             string             `db:"outcome" json:"outcome"`
	ActorUserID         uuid.NullUUID      `db:"actor_user_id" json:"actor_user_id"`
	ActorOrganizationID uuid.NullUUID      `db:"actor_organization_id" json:"actor_organization_id"`
	TargetType          string             `db:"target_type" json:"target_type"`
	TargetID            string             `db:"target_id" json:"target_id"`
	TargetDisplay       string             `db:"target_display" json:"target_display"`
	RequestID           pgtype.Text        `db:"request_id" json:"request_id"`
	TraceID             pgtype.Text        `db:"trace_id" json:"trace_id"`
	SpanID              pgtype.Text        `db:"span_id" json:"span_id"`
	IpAddress           string             `db:"ip_address" json:"ip_address"`
	UserAgent           string             `db:"user_agent" json:"user_agent"`
	MetadataJson        string             `db:"metadata_json" json:"metadata_json"`
	ChangesJson         string             `db:"changes_json" json:"changes_json"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.Category,
		arg.Subcategory,
		arg.EventType,
		arg.Action,
		arg.Outcome,
		arg.ActorUserID,
		arg.ActorOrganizationID,
		arg.TargetType,
		arg.TargetID,
		arg.TargetDisplay,
		arg.RequestID,
		arg.TraceID,
		arg.SpanID,
		arg.IpAddress,
		arg.UserAgent,
		arg.MetadataJson,
		arg.ChangesJson,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
  id, category, subcategory, event_type, action, outcome,
  actor_user_id, actor_organization_id, target_type, target_id, target_display,
  request_id, trace_id, span_id, ip_address, user_agent,
  metadata_json, changes_json, created_at
FROM app_audit_logs
WHERE ($1::text = '' OR category = $2)
  AND ($3::text = '' OR subcategory = $4)
  AND ($5::text = '' OR event_type = $6)
  AND ($7::text = '' OR actor_user_id = $8)
  AND ($9::text = '' OR target_type = $10)
  AND ($11::text = '' OR target_id = $12)
  AND ($13::text = '' OR outcome = $14)
  AND ($15::timestamptz IS NULL OR created_at <= $15)
ORDER BY created_at DESC, id DESC
LIMIT $16
`

type ListAuditLogsParams struct {
	CategoryFilter    string             `db:"category_filter" json:"category_filter"`
	Category          string             `db:"category" json:"category"`
	SubcategoryFilter string             `db:"subcategory_filter" json:"subcategory_filter"`
	Subcategory       string             `db:"subcategory" json:"subcategory"`
	EventTypeFilter   string             `db:"event_type_filter" json:"event_type_filter"`
	EventType         string             `db:"event_type" json:"event_type"`
	ActorUserIDFilter string             `db:"actor_user_id_filter" json:"actor_user_id_filter"`
	ActorUserID       uuid.NullUUID      `db:"actor_user_id" json:"actor_user_id"`
	TargetTypeFilter  string             `db:"target_type_filter" json:"target_type_filter"`
	TargetType        string             `db:"target_type" json:"target_type"`
	TargetIDFilter    string             `db:"target_id_filter" json:"target_id_filter"`
	TargetID          string             `db:"target_id" json:"target_id"`
	OutcomeFilter     string             `db:"outcome_filter" json:"outcome_filter"`
	Outcome           string             `db:"outcome" json:"outcome"`
	Before            pgtype.Timestamptz `db:"before" json:"before"`
	Limit             int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AppAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.CategoryFilter,
		arg.Category,
		arg.SubcategoryFilter,
		arg.Subcategory,
		arg.EventTypeFilter,
		arg.EventType,
		arg.ActorUserIDFilter,
		arg.ActorUserID,
		arg.TargetTypeFilter,
		arg.TargetType,
		arg.TargetIDFilter,
		arg.TargetID,
		arg.OutcomeFilter,
		arg.Outcome,
		arg.Before,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditLog{}
	for rows.Next() {
		var i AppAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Subcategory,
			&i.EventType,
			&i.Action,
			&i.Outcome,
			&i.ActorUserID,
			&i.ActorOrganizationID,
			&i.TargetType,
			&i.TargetID,
			&i.TargetDisplay,
			&i.RequestID,
			&i.TraceID,
			&i.SpanID,
			&i.IpAddress,
			&i.UserAgent,
			&i.MetadataJson,
			&i.ChangesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
