// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO app_audit_logs (
  id, category, subcategory, event_type, action, outcome,
  actor_user_id, actor_organisation_id, target_type, target_id, target_display,
  request_id, trace_id, span_id, ip_address, user_agent,
  metadata_json, changes_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
`

type InsertAuditLogParams struct {
	ID                  uuid.UUID
	Category            string
	Subcategory         string
	EventType           string
	Action              string
	Outcome             string
	ActorUserID         uuid.NullUUID
	ActorOrganisationID uuid.NullUUID
	TargetType          sql.NullString
	TargetID            sql.NullString
	TargetDisplay       sql.NullString
	RequestID           sql.NullString
	TraceID             sql.NullString
	SpanID              sql.NullString
	IpAddress           string
	UserAgent           string
	MetadataJson        string
	ChangesJson         string
	CreatedAt           time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.ID,
		arg.Category,
		arg.Subcategory,
		arg.EventType,
		arg.Action,
		arg.Outcome,
		arg.ActorUserID,
		arg.ActorOrganisationID,
		arg.TargetType,
		arg.TargetID,
		arg.TargetDisplay,
		arg.RequestID,
		arg.TraceID,
		arg.SpanID,
		arg.IpAddress,
		arg.UserAgent,
		arg.MetadataJson,
		arg.ChangesJson,
		arg.CreatedAt,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT
  id, category, subcategory, event_type, action, outcome,
  actor_user_id, actor_organisation_id, target_type, target_id, target_display,
  request_id, trace_id, span_id, ip_address, user_agent,
  metadata_json, changes_json, created_at
FROM app_audit_logs
WHERE ($1 = '' OR category = $2)
  AND ($3 = '' OR subcategory = $4)
  AND ($5 = '' OR event_type = $6)
  AND ($7 = '' OR actor_user_id = $8)
  AND ($9 = '' OR target_type = $10)
  AND ($11 = '' OR target_id = $12)
  AND ($13 = '' OR outcome = $14)
  AND ($16::timestamptz IS NULL OR created_at <= $16)
ORDER BY created_at DESC, id DESC
LIMIT $15
`

type ListAuditLogsParams struct {
	Column1     interface{}
	Category    string
	Column3     interface{}
	Subcategory string
	Column5     interface{}
	EventType   string
	Column7     interface{}
	ActorUserID uuid.NullUUID
	Column9     interface{}
	TargetType  sql.NullString
	Column11    interface{}
	TargetID    sql.NullString
	Column13    interface{}
	Outcome     string
	Limit       int32
	Before      sql.NullTime
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AppAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs,
		arg.Column1,
		arg.Category,
		arg.Column3,
		arg.Subcategory,
		arg.Column5,
		arg.EventType,
		arg.Column7,
		arg.ActorUserID,
		arg.Column9,
		arg.TargetType,
		arg.Column11,
		arg.TargetID,
		arg.Column13,
		arg.Outcome,
		arg.Limit,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditLog{}
	for rows.Next() {
		var i AppAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Subcategory,
			&i.EventType,
			&i.Action,
			&i.Outcome,
			&i.ActorUserID,
			&i.ActorOrganisationID,
			&i.TargetType,
			&i.TargetID,
			&i.TargetDisplay,
			&i.RequestID,
			&i.TraceID,
			&i.SpanID,
			&i.IpAddress,
			&i.UserAgent,
			&i.MetadataJson,
			&i.ChangesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
