// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderAccountID string             `db:"provider_account_id" json:"provider_account_id"`
	PasswordHash      pgtype.Text        `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppAuditLog struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	Category            string             `db:"category" json:"category"`
	Subcategory         string             `db:"subcategory" json:"subcategory"`
	EventType           string             `db:"event_type" json:"event_type"`
	Action              string             `db:"action" json:"action"`
	Outcome             string             `db:"outcome" json:"outcome"`
	ActorUserID         uuid.NullUUID      `db:"actor_user_id" json:"actor_user_id"`
	ActorOrganizationID uuid.NullUUID      `db:"actor_organization_id" json:"actor_organization_id"`
	TargetType          string             `db:"target_type" json:"target_type"`
	TargetID            string             `db:"target_id" json:"target_id"`
	TargetDisplay       string             `db:"target_display" json:"target_display"`
	RequestID           pgtype.Text        `db:"request_id" json:"request_id"`
	TraceID             pgtype.Text        `db:"trace_id" json:"trace_id"`
	SpanID              pgtype.Text        `db:"span_id" json:"span_id"`
	IpAddress           string             `db:"ip_address" json:"ip_address"`
	UserAgent           string             `db:"user_agent" json:"user_agent"`
	MetadataJson        string             `db:"metadata_json" json:"metadata_json"`
	ChangesJson         string             `db:"changes_json" json:"changes_json"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AppSetting struct {
	ID                            string             `db:"id" json:"id"`
	InstanceName                  string             `db:"instance_name" json:"instance_name"`
	SessionIdleTimeoutSeconds     int64              `db:"session_idle_timeout_seconds" json:"session_idle_timeout_seconds"`
	SessionMaxLifetimeSeconds     int64              `db:"session_max_lifetime_seconds" json:"session_max_lifetime_seconds"`
	SessionCleanupIntervalSeconds int64              `db:"session_cleanup_interval_seconds" json:"session_cleanup_interval_seconds"`
	SessionRetentionSeconds       int64              `db:"session_retention_seconds" json:"session_retention_seconds"`
	CreatedAt                     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	Logo      pgtype.Text        `db:"logo" json:"logo"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationInvitation struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Email           string             `db:"email" json:"email"`
	Role            string             `db:"role" json:"role"`
	Status          string             `db:"status" json:"status"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InvitedByUserID uuid.UUID          `db:"invited_by_user_id" json:"invited_by_user_id"`
	AcceptedAt      pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationMember struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Role           string             `db:"role" json:"role"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationRole struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	RoleKey        string             `db:"role_key" json:"role_key"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationRolePermission struct {
	RoleID     uuid.UUID `db:"role_id" json:"role_id"`
	Permission string    `db:"permission" json:"permission"`
}

type Session struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	ActiveOrganizationID uuid.UUID          `db:"active_organization_id" json:"active_organization_id"`
	TokenHash            string             `db:"token_hash" json:"token_hash"`
	IpAddress            string             `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TwoFactor struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Secret                  string             `db:"secret" json:"secret"`
	Verified                bool               `db:"verified" json:"verified"`
	LastUsedStep            pgtype.Int8        `db:"last_used_step" json:"last_used_step"`
	FailedVerificationCount int64              `db:"failed_verification_count" json:"failed_verification_count"`
	LockedUntil             pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastLoginAt     pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VerificationToken struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.NullUUID      `db:"user_id" json:"user_id"`
	Email      string             `db:"email" json:"email"`
	Purpose    string             `db:"purpose" json:"purpose"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
