// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEndedSessionsOlderThan = `-- name: DeleteEndedSessionsOlderThan :execresult
DELETE FROM sessions
WHERE (revoked_at IS NOT NULL OR expires_at < $1) AND updated_at < $2
`

type DeleteEndedSessionsOlderThanParams struct {
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DeleteEndedSessionsOlderThan(ctx context.Context, arg DeleteEndedSessionsOlderThanParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteEndedSessionsOlderThan, arg.ExpiresAt, arg.UpdatedAt)
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, u.email, u.display_name, s.active_organisation_id, o.name AS organisation_name, o.slug AS organisation_slug, m.role,
  COALESCE(array_agg(rp.permission) FILTER (WHERE rp.permission IS NOT NULL), '{}')::text[] AS permissions,
  s.idle_expires_at, s.expires_at, s.revoked_at
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN organisations o ON o.id = s.active_organisation_id
JOIN organisation_members m ON m.user_id = u.id AND m.organisation_id = o.id
LEFT JOIN organisation_roles r ON r.organisation_id = o.id AND r.role_key = m.role
LEFT JOIN organisation_role_permissions rp ON rp.role_id = r.id
WHERE s.token_hash = $1
GROUP BY s.id, u.id, o.id, m.role
`

type GetSessionByTokenHashRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	Email                string             `db:"email" json:"email"`
	DisplayName          string             `db:"display_name" json:"display_name"`
	ActiveOrganisationID uuid.UUID          `db:"active_organisation_id" json:"active_organisation_id"`
	OrganisationName     string             `db:"organisation_name" json:"organisation_name"`
	OrganisationSlug     string             `db:"organisation_slug" json:"organisation_slug"`
	Role                 string             `db:"role" json:"role"`
	Permissions          []string           `db:"permissions" json:"permissions"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.ActiveOrganisationID,
		&i.OrganisationName,
		&i.OrganisationSlug,
		&i.Role,
		&i.Permissions,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, active_organisation_id, token_hash, ip_address, user_agent, last_seen_at, idle_expires_at, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertSessionParams struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	ActiveOrganisationID uuid.UUID          `db:"active_organisation_id" json:"active_organisation_id"`
	TokenHash            string             `db:"token_hash" json:"token_hash"`
	IpAddress            string             `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.ActiveOrganisationID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = $1, updated_at = $2
WHERE token_hash = $3 AND revoked_at IS NULL
`

type RevokeSessionByTokenHashParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, arg.RevokedAt, arg.UpdatedAt, arg.TokenHash)
	return err
}
