// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDefaultSettings = `-- name: EnsureDefaultSettings :exec
INSERT INTO app_settings (
    id,
    instance_name,
    session_idle_timeout_seconds,
    session_max_lifetime_seconds,
    session_cleanup_interval_seconds,
    session_retention_seconds,
    created_at,
    updated_at
) VALUES ('app_settings', 'Dinchy', 1800, 604800, 300, 86400, $1, $2)
ON CONFLICT(id) DO NOTHING
`

type EnsureDefaultSettingsParams struct {
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) EnsureDefaultSettings(ctx context.Context, arg EnsureDefaultSettingsParams) error {
	_, err := q.db.Exec(ctx, ensureDefaultSettings, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const getInstanceName = `-- name: GetInstanceName :one
SELECT instance_name FROM app_settings WHERE id = 'app_settings'
`

func (q *Queries) GetInstanceName(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getInstanceName)
	var instance_name string
	err := row.Scan(&instance_name)
	return instance_name, err
}
