// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_settings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSSOProviderSettings = `-- name: ListSSOProviderSettings :many
SELECT provider_id, client_id, client_secret, callback_url, enabled, created_at, updated_at
FROM sso_provider_settings
ORDER BY provider_id
`

func (q *Queries) ListSSOProviderSettings(ctx context.Context) ([]SsoProviderSetting, error) {
	rows, err := q.db.Query(ctx, listSSOProviderSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoProviderSetting{}
	for rows.Next() {
		var i SsoProviderSetting
		if err := rows.Scan(
			&i.ProviderID,
			&i.ClientID,
			&i.ClientSecret,
			&i.CallbackUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSSOProviderSetting = `-- name: UpsertSSOProviderSetting :exec
INSERT INTO sso_provider_settings (
    provider_id,
    client_id,
    client_secret,
    callback_url,
    enabled,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(provider_id) DO UPDATE SET
    client_id = excluded.client_id,
    client_secret = excluded.client_secret,
    callback_url = excluded.callback_url,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
`

type UpsertSSOProviderSettingParams struct {
	ProviderID   string             `db:"provider_id" json:"provider_id"`
	ClientID     pgtype.Text        `db:"client_id" json:"client_id"`
	ClientSecret pgtype.Text        `db:"client_secret" json:"client_secret"`
	CallbackUrl  pgtype.Text        `db:"callback_url" json:"callback_url"`
	Enabled      bool               `db:"enabled" json:"enabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertSSOProviderSetting(ctx context.Context, arg UpsertSSOProviderSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSSOProviderSetting,
		arg.ProviderID,
		arg.ClientID,
		arg.ClientSecret,
		arg.CallbackUrl,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
