// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const confirmTwoFactor = `-- name: ConfirmTwoFactor :exec
UPDATE two_factors
SET verified = true, last_used_step = $1, failed_verification_count = 0, locked_until = NULL, updated_at = $2
WHERE user_id = $3
`

type ConfirmTwoFactorParams struct {
	LastUsedStep sql.NullInt64
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) ConfirmTwoFactor(ctx context.Context, arg ConfirmTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, confirmTwoFactor, arg.LastUsedStep, arg.UpdatedAt, arg.UserID)
	return err
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :exec
UPDATE verification_tokens
SET consumed_at = $1, updated_at = $2
WHERE id = $3 AND consumed_at IS NULL
`

type ConsumeVerificationTokenParams struct {
	ConsumedAt sql.NullTime
	UpdatedAt  time.Time
	ID         uuid.UUID
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, consumeVerificationToken, arg.ConsumedAt, arg.UpdatedAt, arg.ID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableTwoFactor = `-- name: DisableTwoFactor :exec
DELETE FROM two_factors
WHERE user_id = $1
`

func (q *Queries) DisableTwoFactor(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableTwoFactor, userID)
	return err
}

const findOrganisationByIDForUser = `-- name: FindOrganisationByIDForUser :one
SELECT o.id, o.name, o.slug, m.role
FROM organisation_members m
JOIN organisations o ON o.id = m.organisation_id
WHERE m.user_id = $1 AND o.id = $2
`

type FindOrganisationByIDForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type FindOrganisationByIDForUserRow struct {
	ID   uuid.UUID
	Name string
	Slug string
	Role string
}

func (q *Queries) FindOrganisationByIDForUser(ctx context.Context, arg FindOrganisationByIDForUserParams) (FindOrganisationByIDForUserRow, error) {
	row := q.db.QueryRowContext(ctx, findOrganisationByIDForUser, arg.UserID, arg.ID)
	var i FindOrganisationByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
	)
	return i, err
}

const findOrganisationBySlugForUser = `-- name: FindOrganisationBySlugForUser :one
SELECT o.id, o.name, o.slug, m.role
FROM organisation_members m
JOIN organisations o ON o.id = m.organisation_id
WHERE m.user_id = $1 AND o.slug = $2
`

type FindOrganisationBySlugForUserParams struct {
	UserID uuid.UUID
	Slug   string
}

type FindOrganisationBySlugForUserRow struct {
	ID   uuid.UUID
	Name string
	Slug string
	Role string
}

func (q *Queries) FindOrganisationBySlugForUser(ctx context.Context, arg FindOrganisationBySlugForUserParams) (FindOrganisationBySlugForUserRow, error) {
	row := q.db.QueryRowContext(ctx, findOrganisationBySlugForUser, arg.UserID, arg.Slug)
	var i FindOrganisationBySlugForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
	)
	return i, err
}

const findPasswordAccountByUserID = `-- name: FindPasswordAccountByUserID :one
SELECT id, user_id, provider, provider_account_id, password_hash
FROM accounts
WHERE user_id = $1 AND provider = 'password'
`

type FindPasswordAccountByUserIDRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Provider          string
	ProviderAccountID string
	PasswordHash      sql.NullString
}

func (q *Queries) FindPasswordAccountByUserID(ctx context.Context, userID uuid.UUID) (FindPasswordAccountByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPasswordAccountByUserID, userID)
	var i FindPasswordAccountByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.PasswordHash,
	)
	return i, err
}

const findTwoFactorByUserID = `-- name: FindTwoFactorByUserID :one
SELECT id, user_id, secret, verified, last_used_step, failed_verification_count, locked_until
FROM two_factors
WHERE user_id = $1
`

type FindTwoFactorByUserIDRow struct {
	ID                      uuid.UUID
	UserID                  uuid.UUID
	Secret                  string
	Verified                bool
	LastUsedStep            sql.NullInt64
	FailedVerificationCount int64
	LockedUntil             sql.NullTime
}

func (q *Queries) FindTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (FindTwoFactorByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTwoFactorByUserID, userID)
	var i FindTwoFactorByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.LastUsedStep,
		&i.FailedVerificationCount,
		&i.LockedUntil,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, display_name, disabled_at
FROM users
WHERE email = $1 AND disabled_at IS NULL
`

type FindUserByEmailRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	DisabledAt  sql.NullTime
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
	)
	return i, err
}

const findUserByProviderAccount = `-- name: FindUserByProviderAccount :one
SELECT u.id, u.email, u.display_name, u.disabled_at
FROM accounts a
JOIN users u ON u.id = a.user_id
WHERE a.provider = $1 AND a.provider_account_id = $2 AND u.disabled_at IS NULL
`

type FindUserByProviderAccountParams struct {
	Provider          string
	ProviderAccountID string
}

type FindUserByProviderAccountRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	DisabledAt  sql.NullTime
}

func (q *Queries) FindUserByProviderAccount(ctx context.Context, arg FindUserByProviderAccountParams) (FindUserByProviderAccountRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByProviderAccount, arg.Provider, arg.ProviderAccountID)
	var i FindUserByProviderAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
	)
	return i, err
}

const findVerificationToken = `-- name: FindVerificationToken :one
SELECT id, user_id, email, purpose, token_hash, expires_at, consumed_at
FROM verification_tokens
WHERE token_hash = $1 AND purpose = $2
`

type FindVerificationTokenParams struct {
	TokenHash string
	Purpose   string
}

type FindVerificationTokenRow struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Email      string
	Purpose    string
	TokenHash  string
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
}

func (q *Queries) FindVerificationToken(ctx context.Context, arg FindVerificationTokenParams) (FindVerificationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, findVerificationToken, arg.TokenHash, arg.Purpose)
	var i FindVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, user_id, provider, provider_account_id, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAccountParams struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Provider          string
	ProviderAccountID string
	PasswordHash      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrReplaceTwoFactor = `-- name: InsertOrReplaceTwoFactor :exec
INSERT INTO two_factors (id, user_id, secret, verified, failed_verification_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, 0, $5, $6)
ON CONFLICT(user_id) DO UPDATE SET
  secret = excluded.secret,
  verified = excluded.verified,
  failed_verification_count = 0,
  locked_until = NULL,
  updated_at = excluded.updated_at
`

type InsertOrReplaceTwoFactorParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Secret    string
	Verified  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertOrReplaceTwoFactor(ctx context.Context, arg InsertOrReplaceTwoFactorParams) error {
	_, err := q.db.ExecContext(ctx, insertOrReplaceTwoFactor,
		arg.ID,
		arg.UserID,
		arg.Secret,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganisation = `-- name: InsertOrganisation :exec
INSERT INTO organisations (id, name, slug, logo, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganisationParams struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Logo      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertOrganisation(ctx context.Context, arg InsertOrganisationParams) error {
	_, err := q.db.ExecContext(ctx, insertOrganisation,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganisationMember = `-- name: InsertOrganisationMember :exec
INSERT INTO organisation_members (id, organisation_id, user_id, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganisationMemberParams struct {
	ID             uuid.UUID
	OrganisationID uuid.UUID
	UserID         uuid.UUID
	Role           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertOrganisationMember(ctx context.Context, arg InsertOrganisationMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertOrganisationMember,
		arg.ID,
		arg.OrganisationID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, display_name, email_verified_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	ID              uuid.UUID
	Email           string
	DisplayName     string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec
INSERT INTO verification_tokens (id, user_id, email, purpose, token_hash, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertVerificationTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Email     string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOrganisationsForUser = `-- name: ListOrganisationsForUser :many
SELECT o.id, o.name, o.slug, m.role
FROM organisation_members m
JOIN organisations o ON o.id = m.organisation_id
WHERE m.user_id = $1
ORDER BY o.name
`

type ListOrganisationsForUserRow struct {
	ID   uuid.UUID
	Name string
	Slug string
	Role string
}

func (q *Queries) ListOrganisationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganisationsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganisationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganisationsForUserRow{}
	for rows.Next() {
		var i ListOrganisationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTwoFactorUsed = `-- name: MarkTwoFactorUsed :exec
UPDATE two_factors
SET last_used_step = $1, failed_verification_count = 0, locked_until = NULL, updated_at = $2
WHERE user_id = $3
`

type MarkTwoFactorUsedParams struct {
	LastUsedStep sql.NullInt64
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) MarkTwoFactorUsed(ctx context.Context, arg MarkTwoFactorUsedParams) error {
	_, err := q.db.ExecContext(ctx, markTwoFactorUsed, arg.LastUsedStep, arg.UpdatedAt, arg.UserID)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE sessions
SET revoked_at = $1, updated_at = $2
WHERE user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionsForUserParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsForUser, arg.RevokedAt, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE accounts
SET password_hash = $1, updated_at = $2
WHERE user_id = $3 AND provider = 'password'
`

type UpdateUserPasswordHashParams struct {
	PasswordHash sql.NullString
	UpdatedAt    time.Time
	UserID       uuid.UUID
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.UserID)
	return err
}
