// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTwoFactor = `-- name: ConfirmTwoFactor :exec
UPDATE two_factors
SET verified = true, last_used_step = $1, failed_verification_count = 0, locked_until = NULL, updated_at = $2
WHERE user_id = $3
`

type ConfirmTwoFactorParams struct {
	LastUsedStep pgtype.Int8        `db:"last_used_step" json:"last_used_step"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) ConfirmTwoFactor(ctx context.Context, arg ConfirmTwoFactorParams) error {
	_, err := q.db.Exec(ctx, confirmTwoFactor, arg.LastUsedStep, arg.UpdatedAt, arg.UserID)
	return err
}

const consumeOrganizationInvitation = `-- name: ConsumeOrganizationInvitation :exec
UPDATE organization_invitations
SET status = 'accepted', accepted_at = $1, updated_at = $2
WHERE id = $3 AND status = 'pending' AND accepted_at IS NULL
`

type ConsumeOrganizationInvitationParams struct {
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID         uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) ConsumeOrganizationInvitation(ctx context.Context, arg ConsumeOrganizationInvitationParams) error {
	_, err := q.db.Exec(ctx, consumeOrganizationInvitation, arg.AcceptedAt, arg.UpdatedAt, arg.ID)
	return err
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :exec
UPDATE verification_tokens
SET consumed_at = $1, updated_at = $2
WHERE id = $3 AND consumed_at IS NULL
`

type ConsumeVerificationTokenParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID         uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, consumeVerificationToken, arg.ConsumedAt, arg.UpdatedAt, arg.ID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableTwoFactor = `-- name: DisableTwoFactor :exec
DELETE FROM two_factors
WHERE user_id = $1
`

func (q *Queries) DisableTwoFactor(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableTwoFactor, userID)
	return err
}

const findOrganizationByIDForUser = `-- name: FindOrganizationByIDForUser :one
SELECT o.id, o.name, o.slug, m.role
FROM organization_members m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1 AND o.id = $2
`

type FindOrganizationByIDForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type FindOrganizationByIDForUserRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Slug string    `db:"slug" json:"slug"`
	Role string    `db:"role" json:"role"`
}

func (q *Queries) FindOrganizationByIDForUser(ctx context.Context, arg FindOrganizationByIDForUserParams) (FindOrganizationByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, findOrganizationByIDForUser, arg.UserID, arg.ID)
	var i FindOrganizationByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
	)
	return i, err
}

const findOrganizationBySlugForUser = `-- name: FindOrganizationBySlugForUser :one
SELECT o.id, o.name, o.slug, m.role
FROM organization_members m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1 AND o.slug = $2
`

type FindOrganizationBySlugForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Slug   string    `db:"slug" json:"slug"`
}

type FindOrganizationBySlugForUserRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Slug string    `db:"slug" json:"slug"`
	Role string    `db:"role" json:"role"`
}

func (q *Queries) FindOrganizationBySlugForUser(ctx context.Context, arg FindOrganizationBySlugForUserParams) (FindOrganizationBySlugForUserRow, error) {
	row := q.db.QueryRow(ctx, findOrganizationBySlugForUser, arg.UserID, arg.Slug)
	var i FindOrganizationBySlugForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Role,
	)
	return i, err
}

const findOrganizationInvitationByToken = `-- name: FindOrganizationInvitationByToken :one
SELECT id, organization_id, email, role, status, token_hash, expires_at, invited_by_user_id, accepted_at
FROM organization_invitations
WHERE token_hash = $1
`

type FindOrganizationInvitationByTokenRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Email           string             `db:"email" json:"email"`
	Role            string             `db:"role" json:"role"`
	Status          string             `db:"status" json:"status"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InvitedByUserID uuid.UUID          `db:"invited_by_user_id" json:"invited_by_user_id"`
	AcceptedAt      pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
}

func (q *Queries) FindOrganizationInvitationByToken(ctx context.Context, tokenHash string) (FindOrganizationInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, findOrganizationInvitationByToken, tokenHash)
	var i FindOrganizationInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.InvitedByUserID,
		&i.AcceptedAt,
	)
	return i, err
}

const findPasswordAccountByUserID = `-- name: FindPasswordAccountByUserID :one
SELECT id, user_id, provider, provider_account_id, password_hash
FROM accounts
WHERE user_id = $1 AND provider = 'password'
`

type FindPasswordAccountByUserIDRow struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	UserID            uuid.UUID   `db:"user_id" json:"user_id"`
	Provider          string      `db:"provider" json:"provider"`
	ProviderAccountID string      `db:"provider_account_id" json:"provider_account_id"`
	PasswordHash      pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) FindPasswordAccountByUserID(ctx context.Context, userID uuid.UUID) (FindPasswordAccountByUserIDRow, error) {
	row := q.db.QueryRow(ctx, findPasswordAccountByUserID, userID)
	var i FindPasswordAccountByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.PasswordHash,
	)
	return i, err
}

const findPendingOrganizationInvitationByEmail = `-- name: FindPendingOrganizationInvitationByEmail :one
SELECT id, organization_id, email, role, status, token_hash, expires_at, invited_by_user_id, accepted_at
FROM organization_invitations
WHERE organization_id = $1 AND email = $2 AND status = 'pending' AND accepted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindPendingOrganizationInvitationByEmailParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Email          string    `db:"email" json:"email"`
}

type FindPendingOrganizationInvitationByEmailRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Email           string             `db:"email" json:"email"`
	Role            string             `db:"role" json:"role"`
	Status          string             `db:"status" json:"status"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InvitedByUserID uuid.UUID          `db:"invited_by_user_id" json:"invited_by_user_id"`
	AcceptedAt      pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
}

func (q *Queries) FindPendingOrganizationInvitationByEmail(ctx context.Context, arg FindPendingOrganizationInvitationByEmailParams) (FindPendingOrganizationInvitationByEmailRow, error) {
	row := q.db.QueryRow(ctx, findPendingOrganizationInvitationByEmail, arg.OrganizationID, arg.Email)
	var i FindPendingOrganizationInvitationByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.InvitedByUserID,
		&i.AcceptedAt,
	)
	return i, err
}

const findTwoFactorByUserID = `-- name: FindTwoFactorByUserID :one
SELECT id, user_id, secret, verified, last_used_step, failed_verification_count, locked_until
FROM two_factors
WHERE user_id = $1
`

type FindTwoFactorByUserIDRow struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Secret                  string             `db:"secret" json:"secret"`
	Verified                bool               `db:"verified" json:"verified"`
	LastUsedStep            pgtype.Int8        `db:"last_used_step" json:"last_used_step"`
	FailedVerificationCount int64              `db:"failed_verification_count" json:"failed_verification_count"`
	LockedUntil             pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
}

func (q *Queries) FindTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (FindTwoFactorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, findTwoFactorByUserID, userID)
	var i FindTwoFactorByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Secret,
		&i.Verified,
		&i.LastUsedStep,
		&i.FailedVerificationCount,
		&i.LockedUntil,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, display_name, email_verified_at, disabled_at
FROM users
WHERE email = $1 AND disabled_at IS NULL
`

type FindUserByEmailRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
	)
	return i, err
}

const findUserByProviderAccount = `-- name: FindUserByProviderAccount :one
SELECT u.id, u.email, u.display_name, u.email_verified_at, u.disabled_at
FROM accounts a
JOIN users u ON u.id = a.user_id
WHERE a.provider = $1 AND a.provider_account_id = $2 AND u.disabled_at IS NULL
`

type FindUserByProviderAccountParams struct {
	Provider          string `db:"provider" json:"provider"`
	ProviderAccountID string `db:"provider_account_id" json:"provider_account_id"`
}

type FindUserByProviderAccountRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

func (q *Queries) FindUserByProviderAccount(ctx context.Context, arg FindUserByProviderAccountParams) (FindUserByProviderAccountRow, error) {
	row := q.db.QueryRow(ctx, findUserByProviderAccount, arg.Provider, arg.ProviderAccountID)
	var i FindUserByProviderAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
	)
	return i, err
}

const findVerificationToken = `-- name: FindVerificationToken :one
SELECT id, user_id, email, purpose, token_hash, expires_at, consumed_at
FROM verification_tokens
WHERE token_hash = $1 AND purpose = $2
`

type FindVerificationTokenParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
	Purpose   string `db:"purpose" json:"purpose"`
}

type FindVerificationTokenRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.NullUUID      `db:"user_id" json:"user_id"`
	Email      string             `db:"email" json:"email"`
	Purpose    string             `db:"purpose" json:"purpose"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

func (q *Queries) FindVerificationToken(ctx context.Context, arg FindVerificationTokenParams) (FindVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, findVerificationToken, arg.TokenHash, arg.Purpose)
	var i FindVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, user_id, provider, provider_account_id, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAccountParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	Provider          string             `db:"provider" json:"provider"`
	ProviderAccountID string             `db:"provider_account_id" json:"provider_account_id"`
	PasswordHash      pgtype.Text        `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrReplaceTwoFactor = `-- name: InsertOrReplaceTwoFactor :exec
INSERT INTO two_factors (id, user_id, secret, verified, failed_verification_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, 0, $5, $6)
ON CONFLICT(user_id) DO UPDATE SET
  secret = excluded.secret,
  verified = excluded.verified,
  failed_verification_count = 0,
  locked_until = NULL,
  updated_at = excluded.updated_at
`

type InsertOrReplaceTwoFactorParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Secret    string             `db:"secret" json:"secret"`
	Verified  bool               `db:"verified" json:"verified"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOrReplaceTwoFactor(ctx context.Context, arg InsertOrReplaceTwoFactorParams) error {
	_, err := q.db.Exec(ctx, insertOrReplaceTwoFactor,
		arg.ID,
		arg.UserID,
		arg.Secret,
		arg.Verified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (id, name, slug, logo, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganizationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	Logo      pgtype.Text        `db:"logo" json:"logo"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.Exec(ctx, insertOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganizationInvitation = `-- name: InsertOrganizationInvitation :exec
INSERT INTO organization_invitations (
  id,
  organization_id,
  email,
  role,
  status,
  token_hash,
  expires_at,
  invited_by_user_id,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertOrganizationInvitationParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	Email           string             `db:"email" json:"email"`
	Role            string             `db:"role" json:"role"`
	Status          string             `db:"status" json:"status"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	InvitedByUserID uuid.UUID          `db:"invited_by_user_id" json:"invited_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOrganizationInvitation(ctx context.Context, arg InsertOrganizationInvitationParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganizationMember = `-- name: InsertOrganizationMember :exec
INSERT INTO organization_members (id, organization_id, user_id, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganizationMemberParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Role           string             `db:"role" json:"role"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOrganizationMember(ctx context.Context, arg InsertOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganizationRole = `-- name: InsertOrganizationRole :exec
INSERT INTO organization_roles (id, organization_id, role_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOrganizationRoleParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	RoleKey        string             `db:"role_key" json:"role_key"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertOrganizationRole(ctx context.Context, arg InsertOrganizationRoleParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationRole,
		arg.ID,
		arg.OrganizationID,
		arg.RoleKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganizationRolePermission = `-- name: InsertOrganizationRolePermission :exec
INSERT INTO organization_role_permissions (role_id, permission)
VALUES ($1, $2)
`

type InsertOrganizationRolePermissionParams struct {
	RoleID     uuid.UUID `db:"role_id" json:"role_id"`
	Permission string    `db:"permission" json:"permission"`
}

func (q *Queries) InsertOrganizationRolePermission(ctx context.Context, arg InsertOrganizationRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertOrganizationRolePermission, arg.RoleID, arg.Permission)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, display_name, email_verified_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	DisplayName     string             `db:"display_name" json:"display_name"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec
INSERT INTO verification_tokens (id, user_id, email, purpose, token_hash, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertVerificationTokenParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.NullUUID      `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	Purpose   string             `db:"purpose" json:"purpose"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, m.role
FROM organization_members m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1
ORDER BY o.name
`

type ListOrganizationsForUserRow struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
	Slug string    `db:"slug" json:"slug"`
	Role string    `db:"role" json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTwoFactorUsed = `-- name: MarkTwoFactorUsed :exec
UPDATE two_factors
SET last_used_step = $1, failed_verification_count = 0, locked_until = NULL, updated_at = $2
WHERE user_id = $3
`

type MarkTwoFactorUsedParams struct {
	LastUsedStep pgtype.Int8        `db:"last_used_step" json:"last_used_step"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkTwoFactorUsed(ctx context.Context, arg MarkTwoFactorUsedParams) error {
	_, err := q.db.Exec(ctx, markTwoFactorUsed, arg.LastUsedStep, arg.UpdatedAt, arg.UserID)
	return err
}

const registerTwoFactorFailure = `-- name: RegisterTwoFactorFailure :exec
UPDATE two_factors
SET
  failed_verification_count = failed_verification_count + 1,
  locked_until = CASE
    WHEN failed_verification_count + 1 >= $1 THEN $2
    ELSE locked_until
  END,
  updated_at = $3
WHERE user_id = $4
`

type RegisterTwoFactorFailureParams struct {
	FailureLimit int64              `db:"failure_limit" json:"failure_limit"`
	LockedUntil  pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) RegisterTwoFactorFailure(ctx context.Context, arg RegisterTwoFactorFailureParams) error {
	_, err := q.db.Exec(ctx, registerTwoFactorFailure,
		arg.FailureLimit,
		arg.LockedUntil,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE sessions
SET revoked_at = $1, updated_at = $2
WHERE user_id = $3 AND revoked_at IS NULL
`

type RevokeSessionsForUserParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeSessionsForUser(ctx context.Context, arg RevokeSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsForUser, arg.RevokedAt, arg.UpdatedAt, arg.UserID)
	return err
}

const updateUserEmailVerifiedAt = `-- name: UpdateUserEmailVerifiedAt :exec
UPDATE users
SET email_verified_at = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserEmailVerifiedAtParams struct {
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID              uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateUserEmailVerifiedAt(ctx context.Context, arg UpdateUserEmailVerifiedAtParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerifiedAt, arg.EmailVerifiedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE accounts
SET password_hash = $1, updated_at = $2
WHERE user_id = $3 AND provider = 'password'
`

type UpdateUserPasswordHashParams struct {
	PasswordHash pgtype.Text        `db:"password_hash" json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.UserID)
	return err
}
