// Code generated by cmd/codegen i18n; DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
)

type Code string

const (
	CodeAccountAccessPermissionsAuditLogsRead                Code = "account.access.permissions.audit.logs.read"
	CodeAccountAccessPermissionsAuthInvitationsCreate        Code = "account.access.permissions.auth.invitations.create"
	CodeAccountAccessPermissionsAuthRolesManage              Code = "account.access.permissions.auth.roles.manage"
	CodeAccountAccessRolesAdmin                              Code = "account.access.roles.admin"
	CodeAccountAccessRolesMember                             Code = "account.access.roles.member"
	CodeAccountAuthForbidden                                 Code = "account.auth.forbidden"
	CodeAccountAuthInvalidCredentials                        Code = "account.auth.invalid_credentials"
	CodeAccountAuthInvalidResetToken                         Code = "account.auth.invalid_reset_token"
	CodeAccountAuthInvalidTOTP                               Code = "account.auth.invalid_totp"
	CodeAccountAuthInvitationExists                          Code = "account.auth.invitation_exists"
	CodeAccountAuthInvitationInvalid                         Code = "account.auth.invitation_invalid"
	CodeAccountAuthOIDCInvalidState                          Code = "account.auth.oidc.invalid_state"
	CodeAccountAuthOIDCLoginFailed                           Code = "account.auth.oidc.login_failed"
	CodeAccountAuthOIDCProviderNotFound                      Code = "account.auth.oidc.provider_not_found"
	CodeAccountAuthOrganizationNotFound                      Code = "account.auth.organization_not_found"
	CodeAccountAuthOrganizationRequired                      Code = "account.auth.organization_required"
	CodeAccountAuthSetupCompleted                            Code = "account.auth.setup_completed"
	CodeAccountAuthSSOCacheRequired                          Code = "account.auth.sso.cache_required"
	CodeAccountAuthSSOInvalidState                           Code = "account.auth.sso.invalid_state"
	CodeAccountAuthSSOLoginFailed                            Code = "account.auth.sso.login_failed"
	CodeAccountAuthSSOProviderNotFound                       Code = "account.auth.sso.provider_not_found"
	CodeAccountAuthTOTPLocked                                Code = "account.auth.totp_locked"
	CodeAccountAuthTOTPRequired                              Code = "account.auth.totp_required"
	CodeAccountAuthUnauthenticated                           Code = "account.auth.unauthenticated"
	CodeDiagnosticsAppLoadFrontendAssets                     Code = "diagnostics.app.load_frontend_assets"
	CodeDiagnosticsAppOpenStore                              Code = "diagnostics.app.open_store"
	CodeDiagnosticsAppSetup                                  Code = "diagnostics.app.setup"
	CodeDiagnosticsAppStartTaskRuntime                       Code = "diagnostics.app.start_task_runtime"
	CodeDiagnosticsAuthInvitationAccept                      Code = "diagnostics.auth.invitation.accept"
	CodeDiagnosticsAuthInvitationBeginTx                     Code = "diagnostics.auth.invitation.begin_tx"
	CodeDiagnosticsAuthInvitationCommit                      Code = "diagnostics.auth.invitation.commit"
	CodeDiagnosticsAuthInvitationConsumeInvitation           Code = "diagnostics.auth.invitation.consume_invitation"
	CodeDiagnosticsAuthInvitationCreateInvitation            Code = "diagnostics.auth.invitation.create_invitation"
	CodeDiagnosticsAuthInvitationFindAccount                 Code = "diagnostics.auth.invitation.find_account"
	CodeDiagnosticsAuthInvitationFindInvitation              Code = "diagnostics.auth.invitation.find_invitation"
	CodeDiagnosticsAuthInvitationFindOrganization            Code = "diagnostics.auth.invitation.find_organization"
	CodeDiagnosticsAuthInvitationFindUser                    Code = "diagnostics.auth.invitation.find_user"
	CodeDiagnosticsAuthInvitationGenerateToken               Code = "diagnostics.auth.invitation.generate_token"
	CodeDiagnosticsAuthInvitationPasswordHash                Code = "diagnostics.auth.invitation.password_hash"
	CodeDiagnosticsAuthInvitationRollback                    Code = "diagnostics.auth.invitation.rollback"
	CodeDiagnosticsAuthInvitationSendEmail                   Code = "diagnostics.auth.invitation.send_email"
	CodeDiagnosticsAuthInvitationUpdateEmailVerified         Code = "diagnostics.auth.invitation.update_email_verified"
	CodeDiagnosticsAuthLoginFindAccount                      Code = "diagnostics.auth.login.find_account"
	CodeDiagnosticsAuthLoginFindOrganization                 Code = "diagnostics.auth.login.find_organization"
	CodeDiagnosticsAuthLoginFindUser                         Code = "diagnostics.auth.login.find_user"
	CodeDiagnosticsAuthLoginGenerateToken                    Code = "diagnostics.auth.login.generate_token"
	CodeDiagnosticsAuthLoginListOrganizations                Code = "diagnostics.auth.login.list_organizations"
	CodeDiagnosticsAuthLoginSSOCallback                      Code = "diagnostics.auth.login.sso_callback"
	CodeDiagnosticsAuthLoginSSOStart                         Code = "diagnostics.auth.login.sso_start"
	CodeDiagnosticsAuthLogoutPublishEvent                    Code = "diagnostics.auth.logout.publish_event"
	CodeDiagnosticsAuthPasswordResetConsumeVerificationToken Code = "diagnostics.auth.password_reset.consume_verification_token"
	CodeDiagnosticsAuthPasswordResetCreateVerificationToken  Code = "diagnostics.auth.password_reset.create_verification_token"
	CodeDiagnosticsAuthPasswordResetFindUser                 Code = "diagnostics.auth.password_reset.find_user"
	CodeDiagnosticsAuthPasswordResetFindVerificationToken    Code = "diagnostics.auth.password_reset.find_verification_token"
	CodeDiagnosticsAuthPasswordResetGenerateToken            Code = "diagnostics.auth.password_reset.generate_token"
	CodeDiagnosticsAuthPasswordResetPasswordHash             Code = "diagnostics.auth.password_reset.password_hash"
	CodeDiagnosticsAuthPasswordResetSendEmail                Code = "diagnostics.auth.password_reset.send_email"
	CodeDiagnosticsAuthSessionFindOrganization               Code = "diagnostics.auth.session.find_organization"
	CodeDiagnosticsAuthSetupBeginTx                          Code = "diagnostics.auth.setup.begin_tx"
	CodeDiagnosticsAuthSetupCommit                           Code = "diagnostics.auth.setup.commit"
	CodeDiagnosticsAuthSetupCountUsers                       Code = "diagnostics.auth.setup.count_users"
	CodeDiagnosticsAuthSetupCreateFirstUser                  Code = "diagnostics.auth.setup.create_first_user"
	CodeDiagnosticsAuthSetupInsertAccount                    Code = "diagnostics.auth.setup.insert_account"
	CodeDiagnosticsAuthSetupInsertOrganization               Code = "diagnostics.auth.setup.insert_organization"
	CodeDiagnosticsAuthSetupInsertOrganizationMember         Code = "diagnostics.auth.setup.insert_organization_member"
	CodeDiagnosticsAuthSetupInsertUser                       Code = "diagnostics.auth.setup.insert_user"
	CodeDiagnosticsAuthSetupRollback                         Code = "diagnostics.auth.setup.rollback"
	CodeDiagnosticsAuthTOTPConfirm                           Code = "diagnostics.auth.totp.confirm"
	CodeDiagnosticsAuthTOTPDisable                           Code = "diagnostics.auth.totp.disable"
	CodeDiagnosticsAuthTOTPEnroll                            Code = "diagnostics.auth.totp.enroll"
	CodeDiagnosticsSessionCreateSession                      Code = "diagnostics.session.create_session"
	CodeDiagnosticsSessionGetSession                         Code = "diagnostics.session.get_session"
	CodeDiagnosticsSessionRevokeSession                      Code = "diagnostics.session.revoke_session"
	CodeDiagnosticsSessionRevokeSessionsForUser              Code = "diagnostics.session.revoke_sessions_for_user"
	CodeDiagnosticsStoreClose                                Code = "diagnostics.store.close"
	CodeDiagnosticsStoreEnsureDefaultSettings                Code = "diagnostics.store.ensure_default_settings"
	CodeDiagnosticsStorePing                                 Code = "diagnostics.store.ping"
	CodeDiagnosticsWorkersEventProcessing                    Code = "diagnostics.workers.event_processing"
	CodeDiagnosticsWorkersSessionCleanup                     Code = "diagnostics.workers.session_cleanup"
	CodeNotificationEmailFooter                              Code = "notification.email.footer"
	CodeNotificationEmailInvitationBody                      Code = "notification.email.invitation_body"
	CodeNotificationEmailInvitationCta                       Code = "notification.email.invitation_cta"
	CodeNotificationEmailInvitationHeading                   Code = "notification.email.invitation_heading"
	CodeNotificationEmailInvitationSubject                   Code = "notification.email.invitation_subject"
	CodeNotificationEmailNotConfigured                       Code = "notification.email.not_configured"
	CodeNotificationEmailPasswordResetBody                   Code = "notification.email.password_reset_body"
	CodeNotificationEmailPasswordResetCta                    Code = "notification.email.password_reset_cta"
	CodeNotificationEmailPasswordResetHeading                Code = "notification.email.password_reset_heading"
	CodeNotificationEmailPasswordResetSubject                Code = "notification.email.password_reset_subject"
	CodePlatformConfigLoadFailed                             Code = "platform.config.load_failed"
	CodePlatformConfigValidationFailed                       Code = "platform.config.validation_failed"
	CodePlatformServerInternalError                          Code = "platform.server.internal_error"
	CodeTransportRequestValidationFailed                     Code = "transport.request.validation_failed"
	CodeTransportSecurityCSRFFailed                          Code = "transport.security.csrf_failed"
	CodeTransportSecurityHTTPSRequired                       Code = "transport.security.https_required"
)

var CatalogData = map[language.Tag]map[Code]string{
	language.English: {
		CodeAccountAccessPermissionsAuditLogsRead:                "View audit logs",
		CodeAccountAccessPermissionsAuthInvitationsCreate:        "Create invitations",
		CodeAccountAccessPermissionsAuthRolesManage:              "Manage roles",
		CodeAccountAccessRolesAdmin:                              "Administrator",
		CodeAccountAccessRolesMember:                             "Member",
		CodeAccountAuthForbidden:                                 "You do not have permission to perform this action.",
		CodeAccountAuthInvalidCredentials:                        "Invalid email or password.",
		CodeAccountAuthInvalidResetToken:                         "The password reset token is invalid or has expired.",
		CodeAccountAuthInvalidTOTP:                               "Invalid two-factor authentication code.",
		CodeAccountAuthInvitationExists:                          "An active invitation already exists for that email address.",
		CodeAccountAuthInvitationInvalid:                         "The invitation is invalid or has expired.",
		CodeAccountAuthOIDCInvalidState:                          "The OIDC login flow is invalid or has expired.",
		CodeAccountAuthOIDCLoginFailed:                           "Unable to sign in with that OIDC provider.",
		CodeAccountAuthOIDCProviderNotFound:                      "The selected OIDC provider is not available.",
		CodeAccountAuthOrganizationNotFound:                      "The selected organization is not available.",
		CodeAccountAuthOrganizationRequired:                      "Choose an organization to continue.",
		CodeAccountAuthSetupCompleted:                            "Setup has already been completed for {{.resource}} ({{.count}} users).",
		CodeAccountAuthSSOCacheRequired:                          "A cache store is required before SSO can be enabled.",
		CodeAccountAuthSSOInvalidState:                           "The SSO login flow is invalid or has expired.",
		CodeAccountAuthSSOLoginFailed:                            "Unable to sign in with that SSO provider.",
		CodeAccountAuthSSOProviderNotFound:                       "The selected SSO provider is not available.",
		CodeAccountAuthTOTPLocked:                                "Two-factor authentication is temporarily locked. Try again later.",
		CodeAccountAuthTOTPRequired:                              "Two-factor authentication code required.",
		CodeAccountAuthUnauthenticated:                           "Authentication required.",
		CodeDiagnosticsAppLoadFrontendAssets:                     "Load frontend assets failed",
		CodeDiagnosticsAppOpenStore:                              "Open store failed",
		CodeDiagnosticsAppSetup:                                  "Application setup failed",
		CodeDiagnosticsAppStartTaskRuntime:                       "Start task runtime failed",
		CodeDiagnosticsAuthInvitationAccept:                      "Accept invitation failed",
		CodeDiagnosticsAuthInvitationBeginTx:                     "Begin invitation transaction failed",
		CodeDiagnosticsAuthInvitationCommit:                      "Commit invitation transaction failed",
		CodeDiagnosticsAuthInvitationConsumeInvitation:           "Consume invitation failed",
		CodeDiagnosticsAuthInvitationCreateInvitation:            "Create invitation failed",
		CodeDiagnosticsAuthInvitationFindAccount:                 "Look up password account during invitation failed",
		CodeDiagnosticsAuthInvitationFindInvitation:              "Look up invitation failed",
		CodeDiagnosticsAuthInvitationFindOrganization:            "Resolve organization during invitation failed",
		CodeDiagnosticsAuthInvitationFindUser:                    "Look up user during invitation failed",
		CodeDiagnosticsAuthInvitationGenerateToken:               "Generate invitation token failed",
		CodeDiagnosticsAuthInvitationPasswordHash:                "Hash password during invitation failed",
		CodeDiagnosticsAuthInvitationRollback:                    "Roll back invitation transaction failed",
		CodeDiagnosticsAuthInvitationSendEmail:                   "Send invitation email failed",
		CodeDiagnosticsAuthInvitationUpdateEmailVerified:         "Update email verification during invitation failed",
		CodeDiagnosticsAuthLoginFindAccount:                      "Look up password account during login failed",
		CodeDiagnosticsAuthLoginFindOrganization:                 "Resolve organization during login failed",
		CodeDiagnosticsAuthLoginFindUser:                         "Look up user during login failed",
		CodeDiagnosticsAuthLoginGenerateToken:                    "Generate token during login failed",
		CodeDiagnosticsAuthLoginListOrganizations:                "List organizations during login failed",
		CodeDiagnosticsAuthLoginSSOCallback:                      "Complete SSO login failed",
		CodeDiagnosticsAuthLoginSSOStart:                         "Start SSO login failed",
		CodeDiagnosticsAuthLogoutPublishEvent:                    "Publish logout event failed",
		CodeDiagnosticsAuthPasswordResetConsumeVerificationToken: "Consume password reset verification token failed",
		CodeDiagnosticsAuthPasswordResetCreateVerificationToken:  "Create password reset verification token failed",
		CodeDiagnosticsAuthPasswordResetFindUser:                 "Look up user during password reset failed",
		CodeDiagnosticsAuthPasswordResetFindVerificationToken:    "Look up password reset verification token failed",
		CodeDiagnosticsAuthPasswordResetGenerateToken:            "Generate password reset token failed",
		CodeDiagnosticsAuthPasswordResetPasswordHash:             "Hash password during reset failed",
		CodeDiagnosticsAuthPasswordResetSendEmail:                "Send password reset email failed",
		CodeDiagnosticsAuthSessionFindOrganization:               "Resolve organization during session failed",
		CodeDiagnosticsAuthSetupBeginTx:                          "Begin first-user setup transaction failed",
		CodeDiagnosticsAuthSetupCommit:                           "Commit first-user setup transaction failed",
		CodeDiagnosticsAuthSetupCountUsers:                       "Count users during setup failed",
		CodeDiagnosticsAuthSetupCreateFirstUser:                  "Create first user failed",
		CodeDiagnosticsAuthSetupInsertAccount:                    "Insert account during setup failed",
		CodeDiagnosticsAuthSetupInsertOrganization:               "Insert organization during setup failed",
		CodeDiagnosticsAuthSetupInsertOrganizationMember:         "Insert organization member during setup failed",
		CodeDiagnosticsAuthSetupInsertUser:                       "Insert user during setup failed",
		CodeDiagnosticsAuthSetupRollback:                         "Roll back first-user setup transaction failed",
		CodeDiagnosticsAuthTOTPConfirm:                           "Confirm two-factor authentication failed",
		CodeDiagnosticsAuthTOTPDisable:                           "Disable two-factor authentication failed",
		CodeDiagnosticsAuthTOTPEnroll:                            "Enroll two-factor authentication failed",
		CodeDiagnosticsSessionCreateSession:                      "Create session failed",
		CodeDiagnosticsSessionGetSession:                         "Look up session failed",
		CodeDiagnosticsSessionRevokeSession:                      "Revoke session failed",
		CodeDiagnosticsSessionRevokeSessionsForUser:              "Revoke user sessions failed",
		CodeDiagnosticsStoreClose:                                "Close store failed",
		CodeDiagnosticsStoreEnsureDefaultSettings:                "Ensure default settings failed",
		CodeDiagnosticsStorePing:                                 "Ping store failed",
		CodeDiagnosticsWorkersEventProcessing:                    "Event subscriber processing failed",
		CodeDiagnosticsWorkersSessionCleanup:                     "Session cleanup worker execution failed",
		CodeNotificationEmailFooter:                              "This is an automated message from Dinchy. Please do not reply to this email.",
		CodeNotificationEmailInvitationBody:                      "You have been invited to join {{.organization}} as {{.role}}. Click the button below to accept the invitation and set up your account. This invitation will expire soon.",
		CodeNotificationEmailInvitationCta:                       "Accept invitation",
		CodeNotificationEmailInvitationHeading:                   "Join {{.organization}} on Dinchy",
		CodeNotificationEmailInvitationSubject:                   "You are invited to join {{.organization}} on Dinchy",
		CodeNotificationEmailNotConfigured:                       "Email delivery is not configured.",
		CodeNotificationEmailPasswordResetBody:                   "We received a request to reset your Dinchy password. Click the button below to choose a new one. If you did not request this, you can safely ignore this email.",
		CodeNotificationEmailPasswordResetCta:                    "Reset password",
		CodeNotificationEmailPasswordResetHeading:                "Reset your password",
		CodeNotificationEmailPasswordResetSubject:                "Reset your Dinchy password",
		CodePlatformConfigLoadFailed:                             "Failed to load configuration.",
		CodePlatformConfigValidationFailed:                       "Configuration is invalid.",
		CodePlatformServerInternalError:                          "An unexpected error occurred.",
		CodeTransportRequestValidationFailed:                     "Some fields need attention.",
		CodeTransportSecurityCSRFFailed:                          "Missing or invalid CSRF token.",
		CodeTransportSecurityHTTPSRequired:                       "This endpoint requires a secure (HTTPS) connection.",
	},
}
