// Code generated by cmd/gen event; DO NOT EDIT.

package events

import (
	"sort"
)

type Type string

type Definition struct {
	ID          string
	Type        Type
	Module      string
	Category    string
	Subcategory string
	Action      string
	Outcome     string
	Description string
}

const (
	AuthSecurityAuthLoginFailed     Type = "auth.security.auth.login_failed"
	AuthSecurityAuthLoginSucceeded  Type = "auth.security.auth.login_succeeded"
	AuthSecurityAuthLogoutSucceeded Type = "auth.security.auth.logout_succeeded"
	AuthSecurityAuthSetupCompleted  Type = "auth.security.auth.setup_completed"
	AuthSecuritySSOSettingsUpdated  Type = "auth.security.sso_settings.updated"
	AuthSecurityTwoFactorDisabled   Type = "auth.security.two_factor.disabled"
	AuthSecurityTwoFactorEnabled    Type = "auth.security.two_factor.enabled"
)

var Definitions = map[Type]Definition{
	AuthSecurityAuthLoginFailed: {
		ID:          "login_failed",
		Type:        AuthSecurityAuthLoginFailed,
		Module:      "auth",
		Category:    "security",
		Subcategory: "auth",
		Action:      "login",
		Outcome:     "failed",
		Description: "A login attempt was rejected",
	},
	AuthSecurityAuthLoginSucceeded: {
		ID:          "login_succeeded",
		Type:        AuthSecurityAuthLoginSucceeded,
		Module:      "auth",
		Category:    "security",
		Subcategory: "auth",
		Action:      "login",
		Outcome:     "succeeded",
		Description: "A login attempt was accepted",
	},
	AuthSecurityAuthLogoutSucceeded: {
		ID:          "logout_succeeded",
		Type:        AuthSecurityAuthLogoutSucceeded,
		Module:      "auth",
		Category:    "security",
		Subcategory: "auth",
		Action:      "logout",
		Outcome:     "succeeded",
		Description: "A session was revoked successfully",
	},
	AuthSecurityAuthSetupCompleted: {
		ID:          "setup_completed",
		Type:        AuthSecurityAuthSetupCompleted,
		Module:      "auth",
		Category:    "security",
		Subcategory: "auth",
		Action:      "setup_first_user",
		Outcome:     "succeeded",
		Description: "The initial user setup flow completed",
	},
	AuthSecuritySSOSettingsUpdated: {
		ID:          "updated",
		Type:        AuthSecuritySSOSettingsUpdated,
		Module:      "auth",
		Category:    "security",
		Subcategory: "sso_settings",
		Action:      "update_sso_settings",
		Outcome:     "succeeded",
		Description: "SSO settings were updated",
	},
	AuthSecurityTwoFactorDisabled: {
		ID:          "disabled",
		Type:        AuthSecurityTwoFactorDisabled,
		Module:      "auth",
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "disable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was disabled",
	},
	AuthSecurityTwoFactorEnabled: {
		ID:          "enabled",
		Type:        AuthSecurityTwoFactorEnabled,
		Module:      "auth",
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "enable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was enabled",
	},
}

type AuthSecurityAuthLoginFailedMetadata struct {
	Email  string
	Reason string
}

func (value AuthSecurityAuthLoginFailedMetadata) Map() map[string]any {
	return map[string]any{
		"email":  value.Email,
		"reason": value.Reason,
	}
}

type AuthSecurityAuthLoginFailedChanges struct {
}

func (value AuthSecurityAuthLoginFailedChanges) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityAuthLoginSucceededMetadata struct {
	Email            string
	OrganisationSlug string
}

func (value AuthSecurityAuthLoginSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email":             value.Email,
		"organisation_slug": value.OrganisationSlug,
	}
}

type AuthSecurityAuthLoginSucceededChanges struct {
}

func (value AuthSecurityAuthLoginSucceededChanges) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityAuthLogoutSucceededMetadata struct {
	Email string
}

func (value AuthSecurityAuthLogoutSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email": value.Email,
	}
}

type AuthSecurityAuthLogoutSucceededChanges struct {
}

func (value AuthSecurityAuthLogoutSucceededChanges) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityAuthSetupCompletedMetadata struct {
	Email       string
	DisplayName string
}

func (value AuthSecurityAuthSetupCompletedMetadata) Map() map[string]any {
	return map[string]any{
		"email":        value.Email,
		"display_name": value.DisplayName,
	}
}

type AuthSecurityAuthSetupCompletedChanges struct {
}

func (value AuthSecurityAuthSetupCompletedChanges) Map() map[string]any {
	return map[string]any{}
}

type AuthSecuritySSOSettingsUpdatedMetadata struct {
}

func (value AuthSecuritySSOSettingsUpdatedMetadata) Map() map[string]any {
	return map[string]any{}
}

type AuthSecuritySSOSettingsUpdatedChanges struct {
	ClientID     bool
	ClientSecret bool
	CallbackURL  bool
	Enabled      bool
}

func (value AuthSecuritySSOSettingsUpdatedChanges) Map() map[string]any {
	return map[string]any{
		"client_id":     value.ClientID,
		"client_secret": value.ClientSecret,
		"callback_url":  value.CallbackURL,
		"enabled":       value.Enabled,
	}
}

type AuthSecurityTwoFactorDisabledMetadata struct {
}

func (value AuthSecurityTwoFactorDisabledMetadata) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityTwoFactorDisabledChanges struct {
}

func (value AuthSecurityTwoFactorDisabledChanges) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityTwoFactorEnabledMetadata struct {
}

func (value AuthSecurityTwoFactorEnabledMetadata) Map() map[string]any {
	return map[string]any{}
}

type AuthSecurityTwoFactorEnabledChanges struct {
}

func (value AuthSecurityTwoFactorEnabledChanges) Map() map[string]any {
	return map[string]any{}
}

func DefinitionFor(eventType Type) (Definition, bool) {
	definition, ok := Definitions[eventType]
	return definition, ok
}

func DefinitionsForModule(module string) []Definition {
	out := make([]Definition, 0)
	for _, definition := range Definitions {
		if definition.Module == module {
			out = append(out, definition)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Type < out[j].Type })
	return out
}
