// Code generated by cmd/codegen event; DO NOT EDIT.

package events

const (
	AuthSecurityAuthLoginFailed     Type = "auth.security.auth.login_failed"
	AuthSecurityAuthLoginSucceeded  Type = "auth.security.auth.login_succeeded"
	AuthSecurityAuthLogoutSucceeded Type = "auth.security.auth.logout_succeeded"
	AuthSecurityAuthSetupCompleted  Type = "auth.security.auth.setup_completed"
	AuthSecurityTwoFactorDisabled   Type = "auth.security.two_factor.disabled"
	AuthSecurityTwoFactorEnabled    Type = "auth.security.two_factor.enabled"
)

var Definitions = map[Type]Definition{
	AuthSecurityAuthLoginFailed: {
		ID:           "login_failed",
		Type:         AuthSecurityAuthLoginFailed,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "failed",
		Description:  "A login attempt was rejected",
		MetadataKeys: []string{"email", "reason"},
	},
	AuthSecurityAuthLoginSucceeded: {
		ID:           "login_succeeded",
		Type:         AuthSecurityAuthLoginSucceeded,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "succeeded",
		Description:  "A login attempt was accepted",
		MetadataKeys: []string{"email", "organisation_slug"},
	},
	AuthSecurityAuthLogoutSucceeded: {
		ID:           "logout_succeeded",
		Type:         AuthSecurityAuthLogoutSucceeded,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "logout",
		Outcome:      "succeeded",
		Description:  "A session was revoked successfully",
		MetadataKeys: []string{"email"},
	},
	AuthSecurityAuthSetupCompleted: {
		ID:           "setup_completed",
		Type:         AuthSecurityAuthSetupCompleted,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "setup_first_user",
		Outcome:      "succeeded",
		Description:  "The initial user setup flow completed",
		MetadataKeys: []string{"email", "display_name"},
	},
	AuthSecurityTwoFactorDisabled: {
		ID:          "disabled",
		Type:        AuthSecurityTwoFactorDisabled,
		Path:        []string{"auth", "security", "two_factor"},
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "disable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was disabled",
	},
	AuthSecurityTwoFactorEnabled: {
		ID:          "enabled",
		Type:        AuthSecurityTwoFactorEnabled,
		Path:        []string{"auth", "security", "two_factor"},
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "enable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was enabled",
	},
}

type AuthSecurityAuthLoginFailedMetadata struct {
	Email  string
	Reason string
}

func (value AuthSecurityAuthLoginFailedMetadata) Map() map[string]any {
	return map[string]any{
		"email":  value.Email,
		"reason": value.Reason,
	}
}

func NewAuthSecurityAuthLoginFailedMetadata(email string, reason string) AuthSecurityAuthLoginFailedMetadata {
	return AuthSecurityAuthLoginFailedMetadata{
		Email:  email,
		Reason: reason,
	}
}

type AuthSecurityAuthLoginFailedEvent = TypedEvent[AuthSecurityAuthLoginFailedMetadata, NoChanges]

type AuthSecurityAuthLoginSucceededMetadata struct {
	Email            string
	OrganisationSlug string
}

func (value AuthSecurityAuthLoginSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email":             value.Email,
		"organisation_slug": value.OrganisationSlug,
	}
}

func NewAuthSecurityAuthLoginSucceededMetadata(email string, organisationSlug string) AuthSecurityAuthLoginSucceededMetadata {
	return AuthSecurityAuthLoginSucceededMetadata{
		Email:            email,
		OrganisationSlug: organisationSlug,
	}
}

type AuthSecurityAuthLoginSucceededEvent = TypedEvent[AuthSecurityAuthLoginSucceededMetadata, NoChanges]

type AuthSecurityAuthLogoutSucceededMetadata struct {
	Email string
}

func (value AuthSecurityAuthLogoutSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email": value.Email,
	}
}

func NewAuthSecurityAuthLogoutSucceededMetadata(email string) AuthSecurityAuthLogoutSucceededMetadata {
	return AuthSecurityAuthLogoutSucceededMetadata{
		Email: email,
	}
}

type AuthSecurityAuthLogoutSucceededEvent = TypedEvent[AuthSecurityAuthLogoutSucceededMetadata, NoChanges]

type AuthSecurityAuthSetupCompletedMetadata struct {
	Email       string
	DisplayName string
}

func (value AuthSecurityAuthSetupCompletedMetadata) Map() map[string]any {
	return map[string]any{
		"email":        value.Email,
		"display_name": value.DisplayName,
	}
}

func NewAuthSecurityAuthSetupCompletedMetadata(email string, displayName string) AuthSecurityAuthSetupCompletedMetadata {
	return AuthSecurityAuthSetupCompletedMetadata{
		Email:       email,
		DisplayName: displayName,
	}
}

type AuthSecurityAuthSetupCompletedEvent = TypedEvent[AuthSecurityAuthSetupCompletedMetadata, NoChanges]

type AuthSecurityTwoFactorDisabledMetadata struct {
}

func (value AuthSecurityTwoFactorDisabledMetadata) Map() map[string]any {
	return map[string]any{}
}

func NewAuthSecurityTwoFactorDisabledMetadata() AuthSecurityTwoFactorDisabledMetadata {
	return AuthSecurityTwoFactorDisabledMetadata{}
}

type AuthSecurityTwoFactorDisabledEvent = TypedEvent[AuthSecurityTwoFactorDisabledMetadata, NoChanges]

type AuthSecurityTwoFactorEnabledMetadata struct {
}

func (value AuthSecurityTwoFactorEnabledMetadata) Map() map[string]any {
	return map[string]any{}
}

func NewAuthSecurityTwoFactorEnabledMetadata() AuthSecurityTwoFactorEnabledMetadata {
	return AuthSecurityTwoFactorEnabledMetadata{}
}

type AuthSecurityTwoFactorEnabledEvent = TypedEvent[AuthSecurityTwoFactorEnabledMetadata, NoChanges]
