// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sidarth-23/dinchy/internal/workers (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/sidarth-23/dinchy/internal/workers -destination=internal/workers/store_mockdata_test.go -package=workers github.com/sidarth-23/dinchy/internal/workers Store
//

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	sqlcgen "github.com/sidarth-23/dinchy/internal/platform/store/sqlcgen"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClaimTask mocks base method.
func (m *MockStore) ClaimTask(ctx context.Context, arg sqlcgen.ClaimTaskParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTask", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTask indicates an expected call of ClaimTask.
func (mr *MockStoreMockRecorder) ClaimTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTask", reflect.TypeOf((*MockStore)(nil).ClaimTask), ctx, arg)
}

// DeleteEndedSessionsOlderThan mocks base method.
func (m *MockStore) DeleteEndedSessionsOlderThan(ctx context.Context, arg sqlcgen.DeleteEndedSessionsOlderThanParams) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEndedSessionsOlderThan", ctx, arg)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEndedSessionsOlderThan indicates an expected call of DeleteEndedSessionsOlderThan.
func (mr *MockStoreMockRecorder) DeleteEndedSessionsOlderThan(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEndedSessionsOlderThan", reflect.TypeOf((*MockStore)(nil).DeleteEndedSessionsOlderThan), ctx, arg)
}

// EnsureTask mocks base method.
func (m *MockStore) EnsureTask(ctx context.Context, arg sqlcgen.EnsureTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTask", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureTask indicates an expected call of EnsureTask.
func (mr *MockStoreMockRecorder) EnsureTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTask", reflect.TypeOf((*MockStore)(nil).EnsureTask), ctx, arg)
}

// FinishTask mocks base method.
func (m *MockStore) FinishTask(ctx context.Context, arg sqlcgen.FinishTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishTask", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishTask indicates an expected call of FinishTask.
func (mr *MockStoreMockRecorder) FinishTask(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishTask", reflect.TypeOf((*MockStore)(nil).FinishTask), ctx, arg)
}
