// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sidarth-23/dinchy/internal/workers (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/sidarth-23/dinchy/internal/workers -destination=internal/workers/store_mockdata_test.go -package=workers github.com/sidarth-23/dinchy/internal/workers Store
//

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClaimTask mocks base method.
func (m *MockStore) ClaimTask(ctx context.Context, taskName, owner string, leaseUntil, now time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimTask", ctx, taskName, owner, leaseUntil, now)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimTask indicates an expected call of ClaimTask.
func (mr *MockStoreMockRecorder) ClaimTask(ctx, taskName, owner, leaseUntil, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimTask", reflect.TypeOf((*MockStore)(nil).ClaimTask), ctx, taskName, owner, leaseUntil, now)
}

// DeleteEndedSessionsOlderThan mocks base method.
func (m *MockStore) DeleteEndedSessionsOlderThan(ctx context.Context, olderThan time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEndedSessionsOlderThan", ctx, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEndedSessionsOlderThan indicates an expected call of DeleteEndedSessionsOlderThan.
func (mr *MockStoreMockRecorder) DeleteEndedSessionsOlderThan(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEndedSessionsOlderThan", reflect.TypeOf((*MockStore)(nil).DeleteEndedSessionsOlderThan), ctx, olderThan)
}

// EnsureTask mocks base method.
func (m *MockStore) EnsureTask(ctx context.Context, name string, intervalSeconds int64, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTask", ctx, name, intervalSeconds, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureTask indicates an expected call of EnsureTask.
func (mr *MockStoreMockRecorder) EnsureTask(ctx, name, intervalSeconds, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTask", reflect.TypeOf((*MockStore)(nil).EnsureTask), ctx, name, intervalSeconds, now)
}

// FinishTask mocks base method.
func (m *MockStore) FinishTask(ctx context.Context, taskName string, now time.Time, ok bool, errCode, errMsg string, nextRun time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishTask", ctx, taskName, now, ok, errCode, errMsg, nextRun)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishTask indicates an expected call of FinishTask.
func (mr *MockStoreMockRecorder) FinishTask(ctx, taskName, now, ok, errCode, errMsg, nextRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishTask", reflect.TypeOf((*MockStore)(nil).FinishTask), ctx, taskName, now, ok, errCode, errMsg, nextRun)
}
