// Code generated by cmd/codegen permission; DO NOT EDIT.

package permission

import "github.com/sidarth-23/dinchy/internal/i18n"

type Permission string
type Definition struct {
	Permission                            Permission
	Module, Resource, Action, Description string
	MessageCode                           i18n.Code
}

const (
	AuditLogsRead         Permission = "audit.logs.read"
	AuthInvitationsCreate Permission = "auth.invitations.create"
	AuthRolesManage       Permission = "auth.roles.manage"
)

var definitions = map[Permission]Definition{
	AuditLogsRead:         {Permission: AuditLogsRead, Module: "audit", Resource: "logs", Action: "read", Description: "View organization audit logs", MessageCode: i18n.Code("account.access.permissions.audit.logs.read")},
	AuthInvitationsCreate: {Permission: AuthInvitationsCreate, Module: "auth", Resource: "invitations", Action: "create", Description: "Invite organization members", MessageCode: i18n.Code("account.access.permissions.auth.invitations.create")},
	AuthRolesManage:       {Permission: AuthRolesManage, Module: "auth", Resource: "roles", Action: "manage", Description: "Manage organization roles", MessageCode: i18n.Code("account.access.permissions.auth.roles.manage")},
}

func DefinitionFor(value Permission) (Definition, bool) {
	definition, ok := definitions[value]
	return definition, ok
}
