package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type manifest struct {
	Messages []message `json:"messages"`
}

type message struct {
	Name         string            `json:"name"`
	Code         string            `json:"code"`
	Params       []param           `json:"params"`
	Translations map[string]string `json:"translations"`
}

type param struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

func main() {
	input := flag.String("input", "internal/i18n/messages.json", "manifest input path")
	output := flag.String("output", "internal/i18n/generated.go", "generated Go output path")
	flag.Parse()

	if err := run(*input, *output); err != nil {
		fmt.Fprintf(os.Stderr, "i18ngen: %v\n", err)
		os.Exit(1)
	}
}

func run(inputPath, outputPath string) error {
	raw, err := os.ReadFile(inputPath)
	if err != nil {
		return err
	}

	var mf manifest
	if err := json.Unmarshal(raw, &mf); err != nil {
		return err
	}
	if err := validate(mf); err != nil {
		return err
	}

	src, err := render(mf)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, src, 0o644)
}

func validate(mf manifest) error {
	seenNames := map[string]struct{}{}
	seenCodes := map[string]struct{}{}
	langs := map[string]struct{}{}

	for _, msg := range mf.Messages {
		if msg.Name == "" {
			return fmt.Errorf("message name cannot be empty")
		}
		if msg.Code == "" {
			return fmt.Errorf("message %q has empty code", msg.Name)
		}
		if _, ok := seenNames[msg.Name]; ok {
			return fmt.Errorf("duplicate message name %q", msg.Name)
		}
		if _, ok := seenCodes[msg.Code]; ok {
			return fmt.Errorf("duplicate message code %q", msg.Code)
		}
		seenNames[msg.Name] = struct{}{}
		seenCodes[msg.Code] = struct{}{}

		paramNames := map[string]struct{}{}
		for _, p := range msg.Params {
			if p.Name == "" {
				return fmt.Errorf("message %q has a param with empty name", msg.Name)
			}
			if p.Type == "" {
				return fmt.Errorf("message %q param %q has empty type", msg.Name, p.Name)
			}
			if _, ok := paramNames[p.Name]; ok {
				return fmt.Errorf("message %q has duplicate param %q", msg.Name, p.Name)
			}
			paramNames[p.Name] = struct{}{}
		}

		if len(msg.Translations) == 0 {
			return fmt.Errorf("message %q has no translations", msg.Name)
		}
		for lang, text := range msg.Translations {
			if text == "" {
				return fmt.Errorf("message %q has empty translation for %q", msg.Name, lang)
			}
			langs[lang] = struct{}{}
		}
	}

	if _, ok := langs["en"]; !ok {
		return fmt.Errorf("manifest must include an en translation")
	}
	return nil
}

func render(mf manifest) ([]byte, error) {
	sort.Slice(mf.Messages, func(i, j int) bool { return mf.Messages[i].Code < mf.Messages[j].Code })

	var b strings.Builder
	b.WriteString("// Code generated by cmd/i18ngen; DO NOT EDIT.\n\n")
	b.WriteString("package i18n\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"golang.org/x/text/language\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var CatalogData = map[language.Tag]map[string]string{\n")
	b.WriteString("\tlanguage.English: {\n")
	for _, msg := range mf.Messages {
		translation := msg.Translations["en"]
		fmt.Fprintf(&b, "\t\t%q: %q,\n", msg.Code, translation)
	}
	b.WriteString("\t},\n")
	b.WriteString("}\n\n")

	for _, msg := range mf.Messages {
		fmt.Fprintf(&b, "const Code%s = %q\n\n", msg.Name, msg.Code)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}
