// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sidarth-23/dinchy/internal/access/session (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/sidarth-23/dinchy/internal/access/session -destination=store_mockdata_test.go -package=session . Store
//

// Package session is a generated GoMock package.
package session

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	sqlcgen "github.com/sidarth-23/dinchy/internal/platform/store/sqlcgen"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetActiveSessionTokenHashesForOrganisation mocks base method.
func (m *MockStore) GetActiveSessionTokenHashesForOrganisation(ctx context.Context, activeOrganisationID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionTokenHashesForOrganisation", ctx, activeOrganisationID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSessionTokenHashesForOrganisation indicates an expected call of GetActiveSessionTokenHashesForOrganisation.
func (mr *MockStoreMockRecorder) GetActiveSessionTokenHashesForOrganisation(ctx, activeOrganisationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionTokenHashesForOrganisation", reflect.TypeOf((*MockStore)(nil).GetActiveSessionTokenHashesForOrganisation), ctx, activeOrganisationID)
}

// GetActiveSessionTokenHashesForUser mocks base method.
func (m *MockStore) GetActiveSessionTokenHashesForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionTokenHashesForUser", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSessionTokenHashesForUser indicates an expected call of GetActiveSessionTokenHashesForUser.
func (mr *MockStoreMockRecorder) GetActiveSessionTokenHashesForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionTokenHashesForUser", reflect.TypeOf((*MockStore)(nil).GetActiveSessionTokenHashesForUser), ctx, userID)
}

// GetSessionByTokenHash mocks base method.
func (m *MockStore) GetSessionByTokenHash(ctx context.Context, tokenHash string) (sqlcgen.GetSessionByTokenHashRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(sqlcgen.GetSessionByTokenHashRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByTokenHash indicates an expected call of GetSessionByTokenHash.
func (mr *MockStoreMockRecorder) GetSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).GetSessionByTokenHash), ctx, tokenHash)
}

// InsertSession mocks base method.
func (m *MockStore) InsertSession(ctx context.Context, arg sqlcgen.InsertSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockStoreMockRecorder) InsertSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockStore)(nil).InsertSession), ctx, arg)
}

// RevokeSessionByTokenHash mocks base method.
func (m *MockStore) RevokeSessionByTokenHash(ctx context.Context, arg sqlcgen.RevokeSessionByTokenHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByTokenHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionByTokenHash indicates an expected call of RevokeSessionByTokenHash.
func (mr *MockStoreMockRecorder) RevokeSessionByTokenHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).RevokeSessionByTokenHash), ctx, arg)
}

// RevokeSessionsForUser mocks base method.
func (m *MockStore) RevokeSessionsForUser(ctx context.Context, arg sqlcgen.RevokeSessionsForUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionsForUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionsForUser indicates an expected call of RevokeSessionsForUser.
func (mr *MockStoreMockRecorder) RevokeSessionsForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionsForUser", reflect.TypeOf((*MockStore)(nil).RevokeSessionsForUser), ctx, arg)
}
