// Code generated by cmd/i18ngen; DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
)

type Code string

const (
	CodeAuthInvalidCredentials  Code = "auth.invalid_credentials"
	CodeAuthSetupCompleted      Code = "auth.setup_completed"
	CodeAuthUnauthenticated     Code = "auth.unauthenticated"
	CodeConfigLoadFailed        Code = "config.load_failed"
	CodeConfigValidationFailed  Code = "config.validation_failed"
	CodeRequestValidationFailed Code = "request.validation_failed"
	CodeSecurityCSRFFailed      Code = "security.csrf_failed"
	CodeSecurityHTTPSRequired   Code = "security.https_required"
	CodeServerInternalError     Code = "server.internal_error"
)

var CatalogData = map[language.Tag]map[Code]string{
	language.English: {
		CodeAuthInvalidCredentials:  "Invalid email or password.",
		CodeAuthSetupCompleted:      "Setup has already been completed for {{.resource}} ({{.count}} users).",
		CodeAuthUnauthenticated:     "Authentication required.",
		CodeConfigLoadFailed:        "Failed to load configuration.",
		CodeConfigValidationFailed:  "Configuration is invalid.",
		CodeRequestValidationFailed: "Some fields need attention.",
		CodeSecurityCSRFFailed:      "Missing or invalid CSRF token.",
		CodeSecurityHTTPSRequired:   "This endpoint requires a secure (HTTPS) connection.",
		CodeServerInternalError:     "An unexpected error occurred.",
	},
}
