// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AppSetting struct {
	ID                            string
	InstanceName                  string
	SessionIdleTimeoutSeconds     int64
	SessionMaxLifetimeSeconds     int64
	SessionCleanupIntervalSeconds int64
	SessionRetentionSeconds       int64
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
}

type AuthAuditLog struct {
	ID           uuid.UUID
	EventType    string
	UserID       uuid.NullUUID
	ActorUserID  uuid.NullUUID
	IpAddress    string
	UserAgent    string
	MetadataJson string
	CreatedAt    time.Time
}

type ScheduledTask struct {
	ID                      uuid.UUID
	TaskName                string
	Enabled                 bool
	ScheduleIntervalSeconds int64
	LeaseOwner              sql.NullString
	LeaseExpiresAt          sql.NullTime
	LastRunAt               sql.NullTime
	LastFinishedAt          sql.NullTime
	NextRunAt               sql.NullTime
	LastStatus              sql.NullString
	LastErrorCode           sql.NullString
	LastErrorMessage        sql.NullString
	UpdatedAt               time.Time
}

type Session struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TokenHash     string
	IpAddress     string
	UserAgent     string
	LastSeenAt    time.Time
	IdleExpiresAt time.Time
	ExpiresAt     time.Time
	RevokedAt     sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	DisabledAt   sql.NullTime
	LastLoginAt  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
