// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimTask = `-- name: ClaimTask :execresult
UPDATE scheduled_tasks
SET lease_owner = $1, lease_expires_at = $2, last_run_at = $3, updated_at = $4
WHERE task_name = $5
  AND enabled = TRUE
  AND (lease_expires_at IS NULL OR lease_expires_at < $6)
  AND (next_run_at IS NULL OR next_run_at <= $7)
`

type ClaimTaskParams struct {
	LeaseOwner       sql.NullString
	LeaseExpiresAt   sql.NullTime
	LastRunAt        sql.NullTime
	UpdatedAt        time.Time
	TaskName         string
	LeaseExpiresAt_2 sql.NullTime
	NextRunAt        sql.NullTime
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimTask,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.TaskName,
		arg.LeaseExpiresAt_2,
		arg.NextRunAt,
	)
}

const ensureTask = `-- name: EnsureTask :exec
INSERT INTO scheduled_tasks (id, task_name, enabled, schedule_interval_seconds, next_run_at, updated_at)
VALUES ($1, $2, TRUE, $3, $4, $5)
ON CONFLICT(task_name) DO NOTHING
`

type EnsureTaskParams struct {
	ID                      uuid.UUID
	TaskName                string
	ScheduleIntervalSeconds int64
	NextRunAt               sql.NullTime
	UpdatedAt               time.Time
}

func (q *Queries) EnsureTask(ctx context.Context, arg EnsureTaskParams) error {
	_, err := q.db.ExecContext(ctx, ensureTask,
		arg.ID,
		arg.TaskName,
		arg.ScheduleIntervalSeconds,
		arg.NextRunAt,
		arg.UpdatedAt,
	)
	return err
}

const finishTask = `-- name: FinishTask :exec
UPDATE scheduled_tasks
SET
    lease_owner       = NULL,
    lease_expires_at  = NULL,
    last_finished_at  = $1,
    next_run_at       = $2,
    last_status       = $3,
    last_error_code   = $4,
    last_error_message = $5,
    updated_at        = $6
WHERE task_name = $7
`

type FinishTaskParams struct {
	LastFinishedAt   sql.NullTime
	NextRunAt        sql.NullTime
	LastStatus       sql.NullString
	LastErrorCode    sql.NullString
	LastErrorMessage sql.NullString
	UpdatedAt        time.Time
	TaskName         string
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) error {
	_, err := q.db.ExecContext(ctx, finishTask,
		arg.LastFinishedAt,
		arg.NextRunAt,
		arg.LastStatus,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.TaskName,
	)
	return err
}
