package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"unicode"

	"github.com/stretchr/testify/require"

	manifest "github.com/sidarth-23/dinchy/internal/manifest"
)

func TestGenerateErrorUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join("..", "..", "internal", "errors", "catalog.json")
	require.NoError(t, generateError(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen error; DO NOT EDIT.")
	require.Contains(t, string(got), "package errors")
	require.Contains(t, string(got), "type MetaKey string")
	require.Contains(t, string(got), "type Stage string")
	require.Contains(t, string(got), "type FieldName string")
	require.Contains(t, string(got), "type FieldKind string")
	require.Contains(t, string(got), "func WithFieldName(fieldName FieldName) Option")
	require.Contains(t, string(got), "func WithFieldKind(fieldKind FieldKind) Option")
	require.Contains(t, string(got), "type FieldKind string")
	require.Contains(t, string(got), "func FieldKindOf(kind reflect.Kind) FieldKind")
	require.Contains(t, string(got), "MetaKeyStage")
	require.Contains(t, string(got), "MetaKeyFieldName")
	require.Contains(t, string(got), "MetaKeyFieldKind")
	require.Contains(t, string(got), "MetaKeyDeletedCount")
	require.Contains(t, string(got), "StageOpenStore")
	require.Contains(t, string(got), "HandlerAuthLogin")
	require.Contains(t, string(got), "OperationSQLOpen")
}

func TestGenerateErrorSupportsTypedValues(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	input := filepath.Join(tmpDir, "catalog.json")
	output := filepath.Join(tmpDir, "generated.go")

	raw, err := json.Marshal(errorCatalog{
		Modules: []manifest.ErrorModule{
			{
				Name: "metadata",
				Modules: []manifest.ErrorNode{
					{
						Name:   "deleted_count",
						Type:   "int",
						Values: []any{1, 2, 5},
					},
					{
						Name:   "enabled",
						Type:   "bool",
						Values: []any{true, false},
					},
				},
			},
		},
	})
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(input, raw, 0o644))
	require.NoError(t, generateError(input, output))

	got, err := os.ReadFile(output)
	require.NoError(t, err)
	normalizedGot := normalize(string(got))
	require.Contains(t, normalizedGot, normalize("DeletedCount1 DeletedCount = 1"))
	require.Contains(t, normalizedGot, normalize("DeletedCount2 DeletedCount = 2"))
	require.Contains(t, normalizedGot, normalize("DeletedCount5 DeletedCount = 5"))
	require.Contains(t, normalizedGot, normalize("EnabledTrue Enabled = true"))
	require.Contains(t, normalizedGot, normalize("EnabledFalse Enabled = false"))
}

func TestGenerateI18nUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join("..", "..", "internal", "i18n", "catalog.json")

	raw, err := os.ReadFile(input)
	require.NoError(t, err)

	mf, err := manifest.DecodeI18nCatalog(raw)
	require.NoError(t, err)
	require.NoError(t, generateI18n(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen i18n; DO NOT EDIT.")
	require.Contains(t, string(got), "package i18n")
	require.Contains(t, string(got), "var CatalogData = map[language.Tag]map[Code]string{")

	normalizedGot := normalize(string(got))
	for _, msg := range flattenTestI18nMessages(mf.Modules, nil) {
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+" Code = "+quote(msg.Code)))
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+": "+quote(msg.Translation)))
	}
}

func TestGenerateEventUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join(tmpDir, "catalog.json")
	mf := eventManifest{
		Modules: []eventModule{
			{
				ID: "auth",
				Modules: []eventModule{
					{
						ID: "security",
						Modules: []eventModule{
							{
								ID: "auth",
								Events: []eventDefinition{
									{
										ID:          "login_succeeded",
										Action:      "login",
										Outcome:     "succeeded",
										Description: "A login attempt was accepted",
										MetadataKeys: []manifest.TypedKey{
											{Name: "email", Type: "string"},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
	raw, err := json.Marshal(mf)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(input, raw, 0o644))
	require.NoError(t, generateEvent(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen event; DO NOT EDIT.")
	require.Contains(t, string(got), "package events")
	require.Contains(t, string(got), "type Definition struct")
	require.Contains(t, string(got), "func DefinitionFor(eventType Type) (Definition, bool)")

	normalizedGot := normalize(string(got))
	require.Contains(t, normalizedGot, normalize("AuthSecurityAuthLoginSucceeded Type = "+quote("auth.security.auth.login_succeeded")))
	events := flattenTestEvents(mf.Modules, nil)
	for _, event := range events {
		require.Contains(t, normalizedGot, normalize(event.ConstantName+" Type = "+quote(event.Type)))
		require.Contains(t, normalizedGot, normalize("ID: "+quote(event.ID)))
		require.Contains(t, normalizedGot, normalize("Path: []string{"+quote("auth")+", "+quote("security")+", "+quote("auth")+"}"))
		require.Contains(t, normalizedGot, normalize("Action: "+quote(event.Action)))
		require.Contains(t, normalizedGot, normalize("Outcome: "+quote(event.Outcome)))
		if event.Description != "" {
			require.Contains(t, normalizedGot, normalize("Description: "+quote(event.Description)))
		}
	}
}

func TestValidateErrorCatalogRejectsDuplicateNodeNames(t *testing.T) {
	t.Parallel()

	err := manifest.ValidateErrorCatalog(manifest.ErrorCatalog{
		Modules: []manifest.ErrorModule{
			{
				Name: "metadata",
				Modules: []manifest.ErrorNode{
					{Name: "stage"},
					{Name: "stage"},
				},
			},
		},
	})
	require.Error(t, err)
}

func TestValidateI18nCatalogRejectsMissingEnglishTranslation(t *testing.T) {
	t.Parallel()

	err := manifest.ValidateI18nCatalog(manifest.I18nCatalog{
		Modules: []manifest.I18nModule{
			{
				Name: "auth",
				Messages: []manifest.I18nMessage{
					{Name: "invalid_credentials", Translations: map[string]string{"fr": "bonjour"}},
				},
			},
		},
	})
	require.Error(t, err)
}

func quote(s string) string {
	return strconv.Quote(s)
}

func normalize(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
}

func flattenTestEvents(modules []eventModule, modulePath []string) []flattenedTestEvent {
	out := make([]flattenedTestEvent, 0)
	for _, module := range modules {
		currentModulePath := append(append([]string{}, modulePath...), module.ID)
		for _, event := range module.Events {
			out = append(out, flattenedTestEvent{
				ID:           event.ID,
				Type:         manifest.EventTypeFor(currentModulePath, event.ID),
				Path:         append([]string{}, currentModulePath...),
				Action:       event.Action,
				Outcome:      event.Outcome,
				Description:  event.Description,
				ConstantName: manifest.EventConstantName(currentModulePath, event.ID),
			})
		}
		if len(module.Modules) > 0 {
			out = append(out, flattenTestEvents(module.Modules, currentModulePath)...)
		}
	}
	return out
}

func flattenTestI18nMessages(modules []i18nModule, modulePath []string) []flattenedTestI18nMessage {
	out := make([]flattenedTestI18nMessage, 0)
	for _, module := range modules {
		currentModulePath := append(append([]string{}, modulePath...), module.Name)
		for _, message := range module.Messages {
			out = append(out, flattenedTestI18nMessage{
				ConstantName: manifest.I18nConstantName(currentModulePath, message.Name),
				Code:         manifest.I18nCodeFor(currentModulePath, message.Name),
				Translation:  message.Translations["en"],
			})
		}
		if len(module.Modules) > 0 {
			out = append(out, flattenTestI18nMessages(module.Modules, currentModulePath)...)
		}
	}
	return out
}

type flattenedTestEvent struct {
	ID           string
	Type         string
	Path         []string
	Action       string
	Outcome      string
	Description  string
	ConstantName string
}

type flattenedTestI18nMessage struct {
	ConstantName string
	Code         string
	Translation  string
}
