package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"unicode"

	"github.com/stretchr/testify/require"

	manifest "github.com/sidarth-23/dinchy/internal/manifest"
)

func TestGenerateI18nUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join("..", "..", "internal", "i18n", "catalog.json")

	raw, err := os.ReadFile(input)
	require.NoError(t, err)

	mf, err := manifest.DecodeI18nCatalog(raw)
	require.NoError(t, err)
	require.NoError(t, generateI18n(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen i18n; DO NOT EDIT.")
	require.Contains(t, string(got), "package i18n")
	require.Contains(t, string(got), "var CatalogData = map[language.Tag]map[Code]string{")

	normalizedGot := normalize(string(got))
	for _, msg := range flattenTestI18nMessages(mf.Modules, nil) {
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+" Code = "+quote(msg.Code)))
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+": "+quote(msg.Translation)))
	}
}

func TestGenerateEventUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join(tmpDir, "catalog.json")
	mf := eventManifest{
		Modules: []eventModule{
			{
				ID: "auth",
				Modules: []eventModule{
					{
						ID: "security",
						Modules: []eventModule{
							{
								ID: "auth",
								Events: []eventDefinition{
									{
										ID:          "login_succeeded",
										Action:      "login",
										Outcome:     "succeeded",
										Description: "A login attempt was accepted",
										MetadataKeys: []manifest.Field{
											{Name: "email", Type: "string"},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
	raw, err := json.Marshal(mf)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(input, raw, 0o644))
	require.NoError(t, generateEvent(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen event; DO NOT EDIT.")
	require.Contains(t, string(got), "package events")
	require.Contains(t, string(got), "type Field[K comparable, V any] struct")
	require.Contains(t, string(got), "type Envelope struct")
	require.Contains(t, string(got), "type TypedEvent[M, C mappable] struct")
	require.Contains(t, string(got), "type Event interface")
	require.Contains(t, string(got), "type Definition struct")
	require.Contains(t, string(got), "func DefinitionFor(eventType Type) (Definition, bool)")
	require.NotContains(t, string(got), "TypedKey")
	require.NotContains(t, string(got), "FieldSpec")

	normalizedGot := normalize(string(got))
	require.Contains(t, normalizedGot, normalize("AuthSecurityAuthLoginSucceeded Type = "+quote("auth.security.auth.login_succeeded")))
	events := flattenTestEvents(mf.Modules, nil)
	for _, event := range events {
		require.Contains(t, normalizedGot, normalize(event.ConstantName+" Type = "+quote(event.Type)))
		require.Contains(t, normalizedGot, normalize("ID: "+quote(event.ID)))
		require.Contains(t, normalizedGot, normalize("Path: []string{"+quote("auth")+", "+quote("security")+", "+quote("auth")+"}"))
		require.Contains(t, normalizedGot, normalize("Action: "+quote(event.Action)))
		require.Contains(t, normalizedGot, normalize("Outcome: "+quote(event.Outcome)))
		if event.Description != "" {
			require.Contains(t, normalizedGot, normalize("Description: "+quote(event.Description)))
		}
	}
	require.Contains(t, normalizedGot, normalize("type AuthSecurityAuthLoginSucceededEvent = TypedEvent[AuthSecurityAuthLoginSucceededMetadata, AuthSecurityAuthLoginSucceededChanges]"))
	require.Contains(t, normalizedGot, normalize("type AuthSecurityAuthLoginSucceededMetadataKey string"))
	require.Contains(t, normalizedGot, normalize("func NewAuthSecurityAuthLoginSucceededMetadata(email string) AuthSecurityAuthLoginSucceededMetadata"))
	require.Contains(t, normalizedGot, normalize("Email: Field[AuthSecurityAuthLoginSucceededMetadataKey, string]{Key: AuthSecurityAuthLoginSucceededMetadataKeyEmail, Value: email}"))
}

func TestValidateI18nCatalogRejectsMissingEnglishTranslation(t *testing.T) {
	t.Parallel()

	err := manifest.ValidateI18nCatalog(manifest.I18nCatalog{
		Modules: []manifest.I18nModule{
			{
				Name: "auth",
				Messages: []manifest.I18nMessage{
					{Name: "invalid_credentials", Translations: map[string]string{"fr": "bonjour"}},
				},
			},
		},
	})
	require.Error(t, err)
}

func quote(s string) string {
	return strconv.Quote(s)
}

func normalize(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
}

func flattenTestEvents(modules []eventModule, modulePath []string) []flattenedTestEvent {
	out := make([]flattenedTestEvent, 0)
	for _, module := range modules {
		currentModulePath := append(append([]string{}, modulePath...), module.ID)
		for _, event := range module.Events {
			out = append(out, flattenedTestEvent{
				ID:           event.ID,
				Type:         manifest.EventTypeFor(currentModulePath, event.ID),
				Path:         append([]string{}, currentModulePath...),
				Action:       event.Action,
				Outcome:      event.Outcome,
				Description:  event.Description,
				ConstantName: manifest.EventConstantName(currentModulePath, event.ID),
			})
		}
		if len(module.Modules) > 0 {
			out = append(out, flattenTestEvents(module.Modules, currentModulePath)...)
		}
	}
	return out
}

func flattenTestI18nMessages(modules []i18nModule, modulePath []string) []flattenedTestI18nMessage {
	out := make([]flattenedTestI18nMessage, 0)
	for _, module := range modules {
		currentModulePath := append(append([]string{}, modulePath...), module.Name)
		for _, message := range module.Messages {
			out = append(out, flattenedTestI18nMessage{
				ConstantName: manifest.I18nConstantName(currentModulePath, message.Name),
				Code:         manifest.I18nCodeFor(currentModulePath, message.Name),
				Translation:  message.Translations["en"],
			})
		}
		if len(module.Modules) > 0 {
			out = append(out, flattenTestI18nMessages(module.Modules, currentModulePath)...)
		}
	}
	return out
}

type flattenedTestEvent struct {
	ID           string
	Type         string
	Path         []string
	Action       string
	Outcome      string
	Description  string
	ConstantName string
}

type flattenedTestI18nMessage struct {
	ConstantName string
	Code         string
	Translation  string
}
