package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"unicode"

	"github.com/stretchr/testify/require"

	manifest "github.com/sidarth-23/dinchy/internal/manifest"
)

func TestGenerateI18nUsesSourceManifest(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	out := filepath.Join(tmpDir, "generated.go")
	input := filepath.Join("..", "..", "internal", "foundation", "i18n", "catalog")

	mf, err := manifest.LoadI18nCatalogDir(input)
	require.NoError(t, err)
	require.NoError(t, generateI18n(input, out))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen i18n; DO NOT EDIT.")
	require.Contains(t, string(got), "package i18n")
	require.Contains(t, string(got), "var CatalogData = map[language.Tag]map[Code]string{")

	normalizedGot := normalize(string(got))
	for _, msg := range flattenTestI18nMessages(mf.Modules, nil) {
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+" Code = "+quote(msg.Code)))
		require.Contains(t, normalizedGot, normalize("Code"+msg.ConstantName+": "+quote(msg.Translation)))
	}
}

func TestGenerateEventUsesSourceManifest(t *testing.T) {
	t.Parallel()

	featuresDir := t.TempDir()
	authDir := filepath.Join(featuresDir, "auth")
	require.NoError(t, os.MkdirAll(authDir, 0o755))
	out := filepath.Join(authDir, "events_generated.go")
	mf := eventManifest{
		Modules: []eventModule{
			{
				ID: "auth",
				Modules: []eventModule{
					{
						ID: "security",
						Modules: []eventModule{
							{
								ID: "auth",
								Events: []eventDefinition{
									{
										ID:          "login_succeeded",
										Action:      "login",
										Outcome:     "succeeded",
										Description: "A login attempt was accepted",
										MetadataKeys: []manifest.Field{
											{Name: "email", Type: "string"},
										},
									},
									{
										ID:      "password_changed",
										Action:  "change_password",
										Outcome: "succeeded",
										ChangeKeys: []manifest.Field{
											{Name: "status", Type: "string"},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
	raw, err := json.Marshal(mf)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(authDir, "events.json"), raw, 0o644))
	require.NoError(t, generateEvent(featuresDir))

	got, err := os.ReadFile(out)
	require.NoError(t, err)

	require.Contains(t, string(got), "// Code generated by cmd/codegen event; DO NOT EDIT.")
	require.Contains(t, string(got), "package auth")
	require.Contains(t, string(got), "var EventDefinitions = map[events.Type]events.Definition{")

	// Runtime types stay in the events package; the generated feature file only
	// holds this feature's constants, definitions, and typed events.
	require.NotContains(t, string(got), "package events")
	require.NotContains(t, string(got), "type TypedEvent[")
	require.NotContains(t, string(got), "type Event interface")
	require.NotContains(t, string(got), "var Definitions =")
	require.NotContains(t, string(got), "func DefinitionFor")

	normalizedGot := normalize(string(got))
	// Generated identifiers drop the feature prefix; the catalog type string keeps the full path.
	require.Contains(t, normalizedGot, normalize("SecurityAuthLoginSucceeded events.Type = "+quote("auth.security.auth.login_succeeded")))
	require.Contains(t, normalizedGot, normalize("ID: "+quote("login_succeeded")))
	require.Contains(t, normalizedGot, normalize("Path: []string{"+quote("auth")+", "+quote("security")+", "+quote("auth")+"}"))

	// Metadata is a plain struct; events without change keys use the shared events.NoChanges.
	require.Contains(t, normalizedGot, normalize("type SecurityAuthLoginSucceededMetadata struct {"))
	require.Contains(t, normalizedGot, normalize("Email string"))
	require.Contains(t, normalizedGot, normalize("func NewSecurityAuthLoginSucceededMetadata(email string) SecurityAuthLoginSucceededMetadata"))
	require.Contains(t, normalizedGot, normalize("type SecurityAuthLoginSucceededEvent = events.TypedEvent[SecurityAuthLoginSucceededMetadata, events.NoChanges]"))

	// A change key generates an events.Change[T] pair capturing previous and current values.
	require.Contains(t, normalizedGot, normalize("Status events.Change[string]"))
	require.Contains(t, normalizedGot, normalize(quote("status")+": map[string]any{"+quote("previous")+": value.Status.Previous, "+quote("current")+": value.Status.Current}"))
	require.Contains(t, normalizedGot, normalize("func NewSecurityAuthPasswordChangedChanges(statusPrevious, statusCurrent string) SecurityAuthPasswordChangedChanges"))
	require.Contains(t, normalizedGot, normalize("ChangeKeys: []string{"+quote("status")+"}"))
	require.Contains(t, normalizedGot, normalize("type SecurityAuthPasswordChangedEvent = events.TypedEvent[SecurityAuthPasswordChangedMetadata, SecurityAuthPasswordChangedChanges]"))
}

func TestValidateI18nCatalogRejectsMissingEnglishTranslation(t *testing.T) {
	t.Parallel()

	err := manifest.ValidateI18nCatalog(manifest.I18nCatalog{
		Modules: []manifest.I18nModule{
			{
				Name: "auth",
				Messages: []manifest.I18nMessage{
					{Name: "invalid_credentials", Translations: map[string]string{"fr": "bonjour"}},
				},
			},
		},
	})
	require.Error(t, err)
}

func quote(s string) string {
	return strconv.Quote(s)
}

func normalize(s string) string {
	return strings.Map(func(r rune) rune {
		if unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
}

func flattenTestI18nMessages(modules []i18nModule, modulePath []string) []flattenedTestI18nMessage {
	out := make([]flattenedTestI18nMessage, 0)
	for _, module := range modules {
		currentModulePath := append(append([]string{}, modulePath...), module.Name)
		for _, message := range module.Messages {
			out = append(out, flattenedTestI18nMessage{
				ConstantName: manifest.I18nConstantName(currentModulePath, message.Name),
				Code:         manifest.I18nCodeFor(currentModulePath, message.Name),
				Translation:  message.Translations["en"],
			})
		}
		if len(module.Modules) > 0 {
			out = append(out, flattenTestI18nMessages(module.Modules, currentModulePath)...)
		}
	}
	return out
}

type flattenedTestI18nMessage struct {
	ConstantName string
	Code         string
	Translation  string
}
