package middleware

import (
	"net/http"
)

// apiCSP is the Content-Security-Policy for API responses.
//
// Dinchy serves no documents — Caddy delivers the web UI directly — so this policy governs
// JSON only. It is correspondingly strict: `default-src 'none'` grants nothing, because a
// JSON response has no legitimate reason to load a script, a stylesheet, or a frame. A
// policy naming `script-src 'self'` here would be permission granted for no purpose.
//
// It still matters. A response Content-Type can be wrong, or a browser can be talked into
// treating a JSON body as a document; this policy is what makes that inert.
const apiCSP = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"

// SecureHeaders returns a middleware that applies baseline browser security headers to
// API responses.
//
// Two policies are deliberately not set here, because this handler never sees the response
// they would protect:
//
//   - The document Content-Security-Policy — the one naming script-src, style-src and
//     connect-src — belongs to whoever serves the HTML. That is Caddy in production and the
//     Vite dev server in development, which is also why there is no development variant of
//     the policy above: the relaxations Vite's hot reloading needs are Vite's to declare.
//   - Strict-Transport-Security, because Caddy terminates TLS and the responses that most
//     need it — the HTTP-to-HTTPS redirect and upstream-failure pages — are generated by
//     Caddy and never reach this handler.
func SecureHeaders() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("X-Content-Type-Options", "nosniff")
			w.Header().Set("X-Frame-Options", "DENY")
			w.Header().Set("Content-Security-Policy", apiCSP)
			w.Header().Set("Referrer-Policy", "no-referrer")
			next.ServeHTTP(w, r)
		})
	}
}
