package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type manifest struct {
	Groups []group `json:"groups"`
}

type group struct {
	Name        string  `json:"name"`
	KeyName     string  `json:"key_name,omitempty"`
	OptionName  string  `json:"option_name,omitempty"`
	GoType      string  `json:"go_type,omitempty"`
	MetaKey     string  `json:"meta_key"`
	Comment     string  `json:"comment"`
	Values      []value `json:"values"`
	FromReflect bool    `json:"from_reflect,omitempty"`
}

type value struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func main() {
	input := flag.String("input", "internal/errors/meta.json", "manifest input path")
	output := flag.String("output", "internal/errors/generated.go", "generated Go output path")
	flag.Parse()

	if err := run(*input, *output); err != nil {
		fmt.Fprintf(os.Stderr, "errorgen: %v\n", err)
		os.Exit(1)
	}
}

func run(inputPath, outputPath string) error {
	raw, err := os.ReadFile(inputPath)
	if err != nil {
		return err
	}

	var mf manifest
	if err := json.Unmarshal(raw, &mf); err != nil {
		return err
	}
	if err := validate(mf); err != nil {
		return err
	}

	src, err := render(mf)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, src, 0o644)
}

func validate(mf manifest) error {
	seenNames := map[string]struct{}{}
	seenKeys := map[string]struct{}{}

	for _, group := range mf.Groups {
		if group.Name == "" {
			return fmt.Errorf("group name cannot be empty")
		}
		if group.MetaKey == "" {
			return fmt.Errorf("group %q has empty meta_key", group.Name)
		}
		if _, ok := seenNames[group.Name]; ok {
			return fmt.Errorf("duplicate group name %q", group.Name)
		}
		if _, ok := seenKeys[group.MetaKey]; ok {
			return fmt.Errorf("duplicate meta_key %q", group.MetaKey)
		}
		seenNames[group.Name] = struct{}{}
		seenKeys[group.MetaKey] = struct{}{}

		goType := group.GoType
		if goType == "" {
			goType = "string"
		}
		if goType != "string" && goType != "int" {
			return fmt.Errorf("group %q has unsupported go_type %q", group.Name, goType)
		}

		seenValues := map[string]struct{}{}
		for _, v := range group.Values {
			if v.Name == "" {
				return fmt.Errorf("group %q has a value with empty name", group.Name)
			}
			if v.Value == "" {
				return fmt.Errorf("group %q value %q has empty value", group.Name, v.Name)
			}
			if _, ok := seenValues[v.Name]; ok {
				return fmt.Errorf("group %q has duplicate value name %q", group.Name, v.Name)
			}
			seenValues[v.Name] = struct{}{}
		}
	}
	return nil
}

func render(mf manifest) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/errorgen; DO NOT EDIT.\n\n")
	b.WriteString("package errors\n\n")
	if hasReflect(mf) {
		b.WriteString("import (\n\t\"reflect\"\n)\n\n")
	}

	b.WriteString("type MetaKey string\n\n")
	b.WriteString("const (\n")
	for _, group := range mf.Groups {
		metaKeyName := group.KeyName
		if metaKeyName == "" {
			metaKeyName = group.Name
		}
		fmt.Fprintf(&b, "\tMetaKey%s MetaKey = %q\n", metaKeyName, group.MetaKey)
	}
	b.WriteString(")\n\n")

	for _, group := range mf.Groups {
		if group.Comment != "" {
			fmt.Fprintf(&b, "// %s\n", group.Comment)
		}
		goType := group.GoType
		if goType == "" {
			goType = "string"
		}
		fmt.Fprintf(&b, "type %s %s\n\n", group.Name, goType)
		if group.FromReflect {
			fmt.Fprintf(&b, "func %sOf(kind reflect.Kind) %s { return %s(kind.String()) }\n", group.Name, group.Name, group.Name)
		}
		receiver := strings.ToLower(group.Name[:1])
		metaKeyName := group.KeyName
		if metaKeyName == "" {
			metaKeyName = group.Name
		}
		fmt.Fprintf(&b, "func (%s %s) metaKey() MetaKey { return MetaKey%s }\n", receiver, group.Name, metaKeyName)
		switch goType {
		case "int":
			fmt.Fprintf(&b, "func (%s %s) metaValue() any { return int(%s) }\n", receiver, group.Name, receiver)
		default:
			fmt.Fprintf(&b, "func (%s %s) metaValue() any { return string(%s) }\n", receiver, group.Name, receiver)
		}
		optionName := group.OptionName
		if optionName == "" {
			optionName = "With" + group.Name
		}
		fmt.Fprintf(&b, "func %s(%s %s) Option { return withMetaValue(%s) }\n\n", optionName, receiver, group.Name, receiver)

		if len(group.Values) > 0 {
			b.WriteString("const (\n")
			for _, v := range group.Values {
				fmt.Fprintf(&b, "\t%s %s = %q\n", group.Name+v.Name, group.Name, v.Value)
			}
			b.WriteString(")\n\n")
		}
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func hasReflect(mf manifest) bool {
	for _, group := range mf.Groups {
		if group.FromReflect {
			return true
		}
	}
	return false
}
