// Code generated by cmd/codegen error; DO NOT EDIT.

package errors

import (
	"reflect"
)

type MetaKey string

const (
	MetaKeyDeletedCount MetaKey = "deleted_count"
	MetaKeyFieldKind    MetaKey = "field_kind"
	MetaKeyFieldName    MetaKey = "field_name"
	MetaKeyFlow         MetaKey = "flow"
	MetaKeyHandler      MetaKey = "handler"
	MetaKeyOperation    MetaKey = "operation"
	MetaKeyPath         MetaKey = "path"
	MetaKeyPragma       MetaKey = "pragma"
	MetaKeyStage        MetaKey = "stage"
	MetaKeyTask         MetaKey = "task"
	MetaKeyTokenHash    MetaKey = "token_hash"
)

// Deletion count metadata helpers.
type DeletedCount int

func (deletedCount DeletedCount) metaKey() MetaKey      { return MetaKeyDeletedCount }
func (deletedCount DeletedCount) metaValue() any        { return int(deletedCount) }
func WithDeletedCount(deletedCount DeletedCount) Option { return withMetaValue(deletedCount) }

// FieldKind records a reflected type kind in metadata.
type FieldKind string

func FieldKindOf(kind reflect.Kind) FieldKind  { return FieldKind(kind.String()) }
func (fieldKind FieldKind) metaKey() MetaKey   { return MetaKeyFieldKind }
func (fieldKind FieldKind) metaValue() any     { return string(fieldKind) }
func WithFieldKind(fieldKind FieldKind) Option { return withMetaValue(fieldKind) }

// FieldName records a field name in metadata.
type FieldName string

func (fieldName FieldName) metaKey() MetaKey   { return MetaKeyFieldName }
func (fieldName FieldName) metaValue() any     { return string(fieldName) }
func WithFieldName(fieldName FieldName) Option { return withMetaValue(fieldName) }

// Higher-level business flow metadata helpers.
type Flow string

func (flow Flow) metaKey() MetaKey { return MetaKeyFlow }
func (flow Flow) metaValue() any   { return string(flow) }
func WithFlow(flow Flow) Option    { return withMetaValue(flow) }

const (
	FlowSetupFirstUser Flow = "setup_first_user"
	FlowLogin          Flow = "login"
	FlowSession        Flow = "session"
	FlowLogout         Flow = "logout"
	FlowNewSession     Flow = "new_session"
	FlowTOTP           Flow = "totp"
	FlowPasswordReset  Flow = "password_reset"
)

// Transport handler metadata helpers.
type Handler string

func (handler Handler) metaKey() MetaKey { return MetaKeyHandler }
func (handler Handler) metaValue() any   { return string(handler) }
func WithHandler(handler Handler) Option { return withMetaValue(handler) }

const (
	HandlerAuthLogin         Handler = "auth_login"
	HandlerAuthLogout        Handler = "auth_logout"
	HandlerAuthSession       Handler = "auth_session"
	HandlerAuthSetup         Handler = "auth_setup"
	HandlerAuthOIDCProviders Handler = "auth_oidc_providers"
	HandlerAuthOIDCStart     Handler = "auth_oidc_start"
	HandlerAuthOIDCCallback  Handler = "auth_oidc_callback"
	HandlerAuthSSOStart      Handler = "auth_sso_start"
	HandlerAuthSSOCallback   Handler = "auth_sso_callback"
	HandlerBootstrapGet      Handler = "bootstrap_get"
)

// Storage and runtime operation metadata helpers.
type Operation string

func (operation Operation) metaKey() MetaKey   { return MetaKeyOperation }
func (operation Operation) metaValue() any     { return string(operation) }
func WithOperation(operation Operation) Option { return withMetaValue(operation) }

const (
	OperationEnsureDefaultSettings         Operation = "ensure_default_settings"
	OperationCountUsers                    Operation = "count_users"
	OperationGetInstanceName               Operation = "get_instance_name"
	OperationOpen                          Operation = "open"
	OperationSQLOpen                       Operation = "sql_open"
	OperationPingContext                   Operation = "ping_context"
	OperationClose                         Operation = "close"
	OperationWithTx                        Operation = "with_tx"
	OperationBeginTx                       Operation = "begin_tx"
	OperationCommit                        Operation = "commit"
	OperationRollback                      Operation = "rollback"
	OperationMkdirAll                      Operation = "mkdir_all"
	OperationApplyPragmas                  Operation = "apply_pragmas"
	OperationCreateSession                 Operation = "create_session"
	OperationGetSessionByTokenHash         Operation = "get_session_by_token_hash"
	OperationRevokeSessionByTokenHash      Operation = "revoke_session_by_token_hash"
	OperationDeleteEndedSessionsOlderThan  Operation = "delete_ended_sessions_older_than"
	OperationEnsureTask                    Operation = "ensure_task"
	OperationClaimTask                     Operation = "claim_task"
	OperationFinishTask                    Operation = "finish_task"
	OperationInsertUser                    Operation = "insert_user"
	OperationFindUserByEmail               Operation = "find_user_by_email"
	OperationInsertAccount                 Operation = "insert_account"
	OperationInsertOrganisation            Operation = "insert_organisation"
	OperationInsertOrganisationMember      Operation = "insert_organisation_member"
	OperationFindPasswordAccountByUserID   Operation = "find_password_account_by_user_id"
	OperationFindUserByProviderAccount     Operation = "find_user_by_provider_account"
	OperationListOrganisationsForUser      Operation = "list_organisations_for_user"
	OperationFindOrganisationBySlugForUser Operation = "find_organisation_by_slug_for_user"
	OperationFindOrganisationByIDForUser   Operation = "find_organisation_by_id_for_user"
	OperationUpdateUserPasswordHash        Operation = "update_user_password_hash"
	OperationRevokeSessionsForUser         Operation = "revoke_sessions_for_user"
	OperationInsertVerificationToken       Operation = "insert_verification_token"
	OperationFindVerificationToken         Operation = "find_verification_token"
	OperationConsumeVerificationToken      Operation = "consume_verification_token"
	OperationSaveTwoFactor                 Operation = "save_two_factor"
	OperationFindTwoFactorByUserID         Operation = "find_two_factor_by_user_id"
	OperationConfirmTwoFactor              Operation = "confirm_two_factor"
	OperationMarkTwoFactorUsed             Operation = "mark_two_factor_used"
	OperationDisableTwoFactor              Operation = "disable_two_factor"
)

// Filesystem path metadata helpers.
type Path string

func (path Path) metaKey() MetaKey { return MetaKeyPath }
func (path Path) metaValue() any   { return string(path) }
func WithPath(path Path) Option    { return withMetaValue(path) }

// SQLite pragma metadata helpers.
type Pragma string

func (pragma Pragma) metaKey() MetaKey { return MetaKeyPragma }
func (pragma Pragma) metaValue() any   { return string(pragma) }
func WithPragma(pragma Pragma) Option  { return withMetaValue(pragma) }

// Lifecycle stage metadata helpers.
type Stage string

func (stage Stage) metaKey() MetaKey { return MetaKeyStage }
func (stage Stage) metaValue() any   { return string(stage) }
func WithStage(stage Stage) Option   { return withMetaValue(stage) }

const (
	StageOpenStore                Stage = "open_store"
	StageLoadFrontendAssets       Stage = "load_frontend_assets"
	StageStartTaskRuntime         Stage = "start_task_runtime"
	StageFrontendDistFs           Stage = "frontend_dist_fs"
	StageCreateFirstUser          Stage = "create_first_user"
	StageFindUser                 Stage = "find_user"
	StageGetSession               Stage = "get_session"
	StageRevokeSession            Stage = "revoke_session"
	StageGenerateToken            Stage = "generate_token"
	StageCreateSession            Stage = "create_session"
	StageLogin                    Stage = "login"
	StageBootstrap                Stage = "bootstrap"
	StageSessionLookup            Stage = "session_lookup"
	StageLogout                   Stage = "logout"
	StageSetup                    Stage = "setup"
	StageSetupFirstUser           Stage = "setup_first_user"
	StageOIDCStart                Stage = "oidc_start"
	StageOIDCCallback             Stage = "oidc_callback"
	StageOIDCGenerateState        Stage = "oidc_generate_state"
	StageOIDCGenerateNonce        Stage = "oidc_generate_nonce"
	StageOIDCGenerateVerifier     Stage = "oidc_generate_verifier"
	StageOIDCEncodeState          Stage = "oidc_encode_state"
	StageOIDCAuthorizationURL     Stage = "oidc_authorization_url"
	StageOIDCExchangeCode         Stage = "oidc_exchange_code"
	StageSSOStart                 Stage = "sso_start"
	StageSSOCallback              Stage = "sso_callback"
	StageFindAccount              Stage = "find_account"
	StageFindOrganisation         Stage = "find_organisation"
	StageListOrganisations        Stage = "list_organisations"
	StageTOTPEnroll               Stage = "totp_enroll"
	StageTOTPConfirm              Stage = "totp_confirm"
	StageCreateVerificationToken  Stage = "create_verification_token"
	StageFindVerificationToken    Stage = "find_verification_token"
	StageConsumeVerificationToken Stage = "consume_verification_token"
	StagePasswordHash             Stage = "password_hash"
	StageEnsureTask               Stage = "ensure_task"
	StageClaimTask                Stage = "claim_task"
	StageDeleteEndedSessions      Stage = "delete_ended_sessions"
	StageFinishFailedRun          Stage = "finish_failed_run"
	StageFinishSuccess            Stage = "finish_success"
	StageTxPassthrough            Stage = "tx_passthrough"
	StageBody                     Stage = "body"
	StageRowsAffected             Stage = "rows_affected"
	StageResolveXDGConfigHome     Stage = "resolve_xdg_config_home"
)

// Durable background task metadata helpers.
type Task string

func (task Task) metaKey() MetaKey { return MetaKeyTask }
func (task Task) metaValue() any   { return string(task) }
func WithTask(task Task) Option    { return withMetaValue(task) }

const (
	TaskSessionCleanup Task = "session_cleanup"
)

// Token metadata helpers.
type TokenHash string

func (tokenHash TokenHash) metaKey() MetaKey   { return MetaKeyTokenHash }
func (tokenHash TokenHash) metaValue() any     { return string(tokenHash) }
func WithTokenHash(tokenHash TokenHash) Option { return withMetaValue(tokenHash) }
