// Code generated by cmd/errorgen; DO NOT EDIT.

package errors

import (
	"reflect"
)

type MetaKey string

const (
	MetaKeyStage        MetaKey = "stage"
	MetaKeyFlow         MetaKey = "flow"
	MetaKeyHandler      MetaKey = "handler"
	MetaKeyOperation    MetaKey = "operation"
	MetaKeyTask         MetaKey = "task"
	MetaKeyField        MetaKey = "field"
	MetaKeyKind         MetaKey = "kind"
	MetaKeyPath         MetaKey = "path"
	MetaKeyPragma       MetaKey = "pragma"
	MetaKeyDeletedCount MetaKey = "deleted_count"
	MetaKeyTokenHash    MetaKey = "token_hash"
)

// Stage names a lifecycle step recorded in metadata.
type Stage string

func (s Stage) metaKey() MetaKey { return MetaKeyStage }
func (s Stage) metaValue() any   { return string(s) }
func WithStage(s Stage) Option   { return withMetaValue(s) }

const (
	StageOpenStore            Stage = "open_store"
	StageLoadFrontendAssets   Stage = "load_frontend_assets"
	StageStartTaskRuntime     Stage = "start_task_runtime"
	StageFrontendDistFS       Stage = "frontend_dist_fs"
	StageCreateFirstUser      Stage = "create_first_user"
	StageFindUser             Stage = "find_user"
	StageGetSession           Stage = "get_session"
	StageRevokeSession        Stage = "revoke_session"
	StageGenerateToken        Stage = "generate_token"
	StageCreateSession        Stage = "create_session"
	StageLogin                Stage = "login"
	StageBootstrap            Stage = "bootstrap"
	StageSessionLookup        Stage = "session_lookup"
	StageLogout               Stage = "logout"
	StageSetup                Stage = "setup"
	StageSetupFirstUser       Stage = "setup_first_user"
	StageEnsureTask           Stage = "ensure_task"
	StageClaimTask            Stage = "claim_task"
	StageDeleteEndedSessions  Stage = "delete_ended_sessions"
	StageFinishFailedRun      Stage = "finish_failed_run"
	StageFinishSuccess        Stage = "finish_success"
	StageTxPassthrough        Stage = "tx_passthrough"
	StageBody                 Stage = "body"
	StageRowsAffected         Stage = "rows_affected"
	StageResolveXDGConfigHome Stage = "resolve_xdg_config_home"
)

// Flow names a higher-level business flow recorded in metadata.
type Flow string

func (f Flow) metaKey() MetaKey { return MetaKeyFlow }
func (f Flow) metaValue() any   { return string(f) }
func WithFlow(f Flow) Option    { return withMetaValue(f) }

const (
	FlowSetupFirstUser Flow = "setup_first_user"
	FlowLogin          Flow = "login"
	FlowSession        Flow = "session"
	FlowLogout         Flow = "logout"
	FlowNewSession     Flow = "new_session"
)

// Handler names a transport handler recorded in metadata.
type Handler string

func (h Handler) metaKey() MetaKey { return MetaKeyHandler }
func (h Handler) metaValue() any   { return string(h) }
func WithHandler(h Handler) Option { return withMetaValue(h) }

const (
	HandlerAuthLogin    Handler = "auth.login"
	HandlerAuthLogout   Handler = "auth.logout"
	HandlerAuthSession  Handler = "auth.session"
	HandlerAuthSetup    Handler = "auth.setup"
	HandlerBootstrapGet Handler = "bootstrap.get"
)

// Operation names a storage or runtime operation recorded in metadata.
type Operation string

func (o Operation) metaKey() MetaKey   { return MetaKeyOperation }
func (o Operation) metaValue() any     { return string(o) }
func WithOperation(o Operation) Option { return withMetaValue(o) }

const (
	OperationEnsureDefaultSettings        Operation = "EnsureDefaultSettings"
	OperationCountUsers                   Operation = "CountUsers"
	OperationGetInstanceName              Operation = "GetInstanceName"
	OperationOpen                         Operation = "Open"
	OperationSQLOpen                      Operation = "sql.Open"
	OperationPingContext                  Operation = "PingContext"
	OperationClose                        Operation = "Close"
	OperationWithTx                       Operation = "WithTx"
	OperationBeginTx                      Operation = "BeginTx"
	OperationCommit                       Operation = "Commit"
	OperationRollback                     Operation = "Rollback"
	OperationMkdirAll                     Operation = "MkdirAll"
	OperationApplyPragmas                 Operation = "applyPragmas"
	OperationCreateSession                Operation = "CreateSession"
	OperationGetSessionByTokenHash        Operation = "GetSessionByTokenHash"
	OperationRevokeSessionByTokenHash     Operation = "RevokeSessionByTokenHash"
	OperationDeleteEndedSessionsOlderThan Operation = "DeleteEndedSessionsOlderThan"
	OperationEnsureTask                   Operation = "EnsureTask"
	OperationClaimTask                    Operation = "ClaimTask"
	OperationFinishTask                   Operation = "FinishTask"
	OperationInsertUser                   Operation = "InsertUser"
	OperationFindUserByEmail              Operation = "FindUserByEmail"
)

// Task names a durable background task recorded in metadata.
type Task string

func (t Task) metaKey() MetaKey { return MetaKeyTask }
func (t Task) metaValue() any   { return string(t) }
func WithTask(t Task) Option    { return withMetaValue(t) }

const (
	TaskSessionCleanup Task = "session_cleanup"
)

// FieldName records a field name in metadata.
type FieldName string

func (f FieldName) metaKey() MetaKey { return MetaKeyField }
func (f FieldName) metaValue() any   { return string(f) }
func WithField(f FieldName) Option   { return withMetaValue(f) }

// FieldKind records a reflected type kind in metadata.
type FieldKind string

func FieldKindOf(kind reflect.Kind) FieldKind { return FieldKind(kind.String()) }
func (f FieldKind) metaKey() MetaKey          { return MetaKeyKind }
func (f FieldKind) metaValue() any            { return string(f) }
func WithKind(f FieldKind) Option             { return withMetaValue(f) }

// Path records a filesystem path in metadata.
type Path string

func (p Path) metaKey() MetaKey { return MetaKeyPath }
func (p Path) metaValue() any   { return string(p) }
func WithPath(p Path) Option    { return withMetaValue(p) }

// Pragma records a SQLite pragma name in metadata.
type Pragma string

func (p Pragma) metaKey() MetaKey { return MetaKeyPragma }
func (p Pragma) metaValue() any   { return string(p) }
func WithPragma(p Pragma) Option  { return withMetaValue(p) }

// DeletedCount records the number of deleted rows in metadata.
type DeletedCount int

func (d DeletedCount) metaKey() MetaKey      { return MetaKeyDeletedCount }
func (d DeletedCount) metaValue() any        { return int(d) }
func WithDeletedCount(d DeletedCount) Option { return withMetaValue(d) }

// TokenHash records a token hash in metadata.
type TokenHash string

func (t TokenHash) metaKey() MetaKey   { return MetaKeyTokenHash }
func (t TokenHash) metaValue() any     { return string(t) }
func WithTokenHash(t TokenHash) Option { return withMetaValue(t) }
