// Code generated by cmd/gen event; DO NOT EDIT.

package eventcatalog

type Type string

type Subscriber string

const (
	SubscriberAudit Subscriber = "audit"
)

type Definition struct {
	Name         string
	Type         Type
	Module       string
	Subscriber   Subscriber
	Category     string
	Subcategory  string
	Action       string
	Outcome      string
	MetadataKeys []string
	ChangeKeys   []string
}

const (
	AuthLoginFailed        Type = "auth.login_failed"
	AuthLoginSucceeded     Type = "auth.login_succeeded"
	AuthSetupCompleted     Type = "auth.setup_completed"
	AuthLogoutSucceeded    Type = "auth.logout_succeeded"
	AuthTwoFactorEnabled   Type = "auth.two_factor_enabled"
	AuthTwoFactorDisabled  Type = "auth.two_factor_disabled"
	AuthSSOSettingsUpdated Type = "auth.sso_settings_updated"
)

var Definitions = map[Type]Definition{
	AuthLoginFailed: {
		Name:         "AuthLoginFailed",
		Type:         AuthLoginFailed,
		Module:       "auth",
		Subscriber:   SubscriberAudit,
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "failed",
		MetadataKeys: []string{"email"},
	},
	AuthLoginSucceeded: {
		Name:         "AuthLoginSucceeded",
		Type:         AuthLoginSucceeded,
		Module:       "auth",
		Subscriber:   SubscriberAudit,
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "succeeded",
		MetadataKeys: []string{"email", "organisation_slug"},
	},
	AuthSetupCompleted: {
		Name:         "AuthSetupCompleted",
		Type:         AuthSetupCompleted,
		Module:       "auth",
		Subscriber:   SubscriberAudit,
		Category:     "security",
		Subcategory:  "auth",
		Action:       "setup_first_user",
		Outcome:      "succeeded",
		MetadataKeys: []string{"email", "display_name"},
	},
	AuthLogoutSucceeded: {
		Name:         "AuthLogoutSucceeded",
		Type:         AuthLogoutSucceeded,
		Module:       "auth",
		Subscriber:   SubscriberAudit,
		Category:     "security",
		Subcategory:  "auth",
		Action:       "logout",
		Outcome:      "succeeded",
		MetadataKeys: []string{"email"},
	},
	AuthTwoFactorEnabled: {
		Name:        "AuthTwoFactorEnabled",
		Type:        AuthTwoFactorEnabled,
		Module:      "auth",
		Subscriber:  SubscriberAudit,
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "enable_totp",
		Outcome:     "succeeded",
	},
	AuthTwoFactorDisabled: {
		Name:        "AuthTwoFactorDisabled",
		Type:        AuthTwoFactorDisabled,
		Module:      "auth",
		Subscriber:  SubscriberAudit,
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "disable_totp",
		Outcome:     "succeeded",
	},
	AuthSSOSettingsUpdated: {
		Name:        "AuthSSOSettingsUpdated",
		Type:        AuthSSOSettingsUpdated,
		Module:      "auth",
		Subscriber:  SubscriberAudit,
		Category:    "security",
		Subcategory: "sso_settings",
		Action:      "update_sso_settings",
		Outcome:     "succeeded",
		ChangeKeys:  []string{"client_id", "client_secret", "callback_url", "enabled"},
	},
}

var SubscriberDefinitions = map[Subscriber][]Type{
	SubscriberAudit: {
		AuthLoginFailed,
		AuthLoginSucceeded,
		AuthSetupCompleted,
		AuthLogoutSucceeded,
		AuthTwoFactorEnabled,
		AuthTwoFactorDisabled,
		AuthSSOSettingsUpdated,
	},
}

func DefinitionFor(eventType Type) (Definition, bool) {
	definition, ok := Definitions[eventType]
	return definition, ok
}

func EventsForSubscriber(subscriber Subscriber) []Definition {
	types := SubscriberDefinitions[subscriber]
	out := make([]Definition, 0, len(types))
	for _, eventType := range types {
		if definition, ok := Definitions[eventType]; ok {
			out = append(out, definition)
		}
	}
	return out
}
