// Code generated by cmd/codegen event; DO NOT EDIT.

package auth

import (
	"github.com/sidarth-23/dinchy/internal/events"
)

const (
	SecurityAuthLoginFailed     events.Type = "auth.security.auth.login_failed"
	SecurityAuthLoginSucceeded  events.Type = "auth.security.auth.login_succeeded"
	SecurityAuthLogoutSucceeded events.Type = "auth.security.auth.logout_succeeded"
	SecurityAuthSetupCompleted  events.Type = "auth.security.auth.setup_completed"
	SecurityTwoFactorDisabled   events.Type = "auth.security.two_factor.disabled"
	SecurityTwoFactorEnabled    events.Type = "auth.security.two_factor.enabled"
)

// EventDefinitions is this feature's event catalog, registered on the event bus
// at wiring time.
var EventDefinitions = map[events.Type]events.Definition{
	SecurityAuthLoginFailed: {
		ID:           "login_failed",
		Type:         SecurityAuthLoginFailed,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "failed",
		Description:  "A login attempt was rejected",
		MetadataKeys: []string{"email", "reason"},
	},
	SecurityAuthLoginSucceeded: {
		ID:           "login_succeeded",
		Type:         SecurityAuthLoginSucceeded,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "login",
		Outcome:      "succeeded",
		Description:  "A login attempt was accepted",
		MetadataKeys: []string{"email", "organization_slug"},
	},
	SecurityAuthLogoutSucceeded: {
		ID:           "logout_succeeded",
		Type:         SecurityAuthLogoutSucceeded,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "logout",
		Outcome:      "succeeded",
		Description:  "A session was revoked successfully",
		MetadataKeys: []string{"email"},
	},
	SecurityAuthSetupCompleted: {
		ID:           "setup_completed",
		Type:         SecurityAuthSetupCompleted,
		Path:         []string{"auth", "security", "auth"},
		Category:     "security",
		Subcategory:  "auth",
		Action:       "setup_first_user",
		Outcome:      "succeeded",
		Description:  "The initial user setup flow completed",
		MetadataKeys: []string{"email", "display_name"},
	},
	SecurityTwoFactorDisabled: {
		ID:          "disabled",
		Type:        SecurityTwoFactorDisabled,
		Path:        []string{"auth", "security", "two_factor"},
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "disable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was disabled",
	},
	SecurityTwoFactorEnabled: {
		ID:          "enabled",
		Type:        SecurityTwoFactorEnabled,
		Path:        []string{"auth", "security", "two_factor"},
		Category:    "security",
		Subcategory: "two_factor",
		Action:      "enable_totp",
		Outcome:     "succeeded",
		Description: "Two-factor authentication was enabled",
	},
}

type SecurityAuthLoginFailedMetadata struct {
	Email  string
	Reason string
}

func (value SecurityAuthLoginFailedMetadata) Map() map[string]any {
	return map[string]any{
		"email":  value.Email,
		"reason": value.Reason,
	}
}

func NewSecurityAuthLoginFailedMetadata(email string, reason string) SecurityAuthLoginFailedMetadata {
	return SecurityAuthLoginFailedMetadata{
		Email:  email,
		Reason: reason,
	}
}

type SecurityAuthLoginFailedEvent = events.TypedEvent[SecurityAuthLoginFailedMetadata, events.NoChanges]

type SecurityAuthLoginSucceededMetadata struct {
	Email            string
	OrganizationSlug string
}

func (value SecurityAuthLoginSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email":             value.Email,
		"organization_slug": value.OrganizationSlug,
	}
}

func NewSecurityAuthLoginSucceededMetadata(email string, organizationSlug string) SecurityAuthLoginSucceededMetadata {
	return SecurityAuthLoginSucceededMetadata{
		Email:            email,
		OrganizationSlug: organizationSlug,
	}
}

type SecurityAuthLoginSucceededEvent = events.TypedEvent[SecurityAuthLoginSucceededMetadata, events.NoChanges]

type SecurityAuthLogoutSucceededMetadata struct {
	Email string
}

func (value SecurityAuthLogoutSucceededMetadata) Map() map[string]any {
	return map[string]any{
		"email": value.Email,
	}
}

func NewSecurityAuthLogoutSucceededMetadata(email string) SecurityAuthLogoutSucceededMetadata {
	return SecurityAuthLogoutSucceededMetadata{
		Email: email,
	}
}

type SecurityAuthLogoutSucceededEvent = events.TypedEvent[SecurityAuthLogoutSucceededMetadata, events.NoChanges]

type SecurityAuthSetupCompletedMetadata struct {
	Email       string
	DisplayName string
}

func (value SecurityAuthSetupCompletedMetadata) Map() map[string]any {
	return map[string]any{
		"email":        value.Email,
		"display_name": value.DisplayName,
	}
}

func NewSecurityAuthSetupCompletedMetadata(email string, displayName string) SecurityAuthSetupCompletedMetadata {
	return SecurityAuthSetupCompletedMetadata{
		Email:       email,
		DisplayName: displayName,
	}
}

type SecurityAuthSetupCompletedEvent = events.TypedEvent[SecurityAuthSetupCompletedMetadata, events.NoChanges]

type SecurityTwoFactorDisabledMetadata struct {
}

func (value SecurityTwoFactorDisabledMetadata) Map() map[string]any {
	return map[string]any{}
}

func NewSecurityTwoFactorDisabledMetadata() SecurityTwoFactorDisabledMetadata {
	return SecurityTwoFactorDisabledMetadata{}
}

type SecurityTwoFactorDisabledEvent = events.TypedEvent[SecurityTwoFactorDisabledMetadata, events.NoChanges]

type SecurityTwoFactorEnabledMetadata struct {
}

func (value SecurityTwoFactorEnabledMetadata) Map() map[string]any {
	return map[string]any{}
}

func NewSecurityTwoFactorEnabledMetadata() SecurityTwoFactorEnabledMetadata {
	return SecurityTwoFactorEnabledMetadata{}
}

type SecurityTwoFactorEnabledEvent = events.TypedEvent[SecurityTwoFactorEnabledMetadata, events.NoChanges]
