// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sidarth-23/dinchy/internal/features/auth (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=internal/features/auth/mock_store_test.go -package=auth github.com/sidarth-23/dinchy/internal/features/auth Store
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	session "github.com/sidarth-23/dinchy/internal/features/session"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateFirstUser mocks base method.
func (m *MockStore) CreateFirstUser(ctx context.Context, in CreateUserInput) (User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFirstUser", ctx, in)
	ret0, _ := ret[0].(User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFirstUser indicates an expected call of CreateFirstUser.
func (mr *MockStoreMockRecorder) CreateFirstUser(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFirstUser", reflect.TypeOf((*MockStore)(nil).CreateFirstUser), ctx, in)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, in session.CreateSessionInput) (session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, in)
	ret0, _ := ret[0].(session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, in)
}

// FindUserByEmail mocks base method.
func (m *MockStore) FindUserByEmail(ctx context.Context, email string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockStoreMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockStore)(nil).FindUserByEmail), ctx, email)
}

// GetSessionByTokenHash mocks base method.
func (m *MockStore) GetSessionByTokenHash(ctx context.Context, tokenHash string) (*session.SessionWithUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*session.SessionWithUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByTokenHash indicates an expected call of GetSessionByTokenHash.
func (mr *MockStoreMockRecorder) GetSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).GetSessionByTokenHash), ctx, tokenHash)
}

// RevokeSessionByTokenHash mocks base method.
func (m *MockStore) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionByTokenHash indicates an expected call of RevokeSessionByTokenHash.
func (mr *MockStoreMockRecorder) RevokeSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).RevokeSessionByTokenHash), ctx, tokenHash)
}
