// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/features/auth (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/sidarth-23/dinchy/internal/features/auth -destination=internal/features/auth/store_mockdata_test.go -package=auth ./internal/features/auth Store
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"

	sqlcgen "github.com/sidarth-23/dinchy/internal/platform/store/sqlcgen"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ConfirmTwoFactor mocks base method.
func (m *MockStore) ConfirmTwoFactor(ctx context.Context, arg sqlcgen.ConfirmTwoFactorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTwoFactor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmTwoFactor indicates an expected call of ConfirmTwoFactor.
func (mr *MockStoreMockRecorder) ConfirmTwoFactor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTwoFactor", reflect.TypeOf((*MockStore)(nil).ConfirmTwoFactor), ctx, arg)
}

// ConsumeOrganizationInvitation mocks base method.
func (m *MockStore) ConsumeOrganizationInvitation(ctx context.Context, arg sqlcgen.ConsumeOrganizationInvitationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOrganizationInvitation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeOrganizationInvitation indicates an expected call of ConsumeOrganizationInvitation.
func (mr *MockStoreMockRecorder) ConsumeOrganizationInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOrganizationInvitation", reflect.TypeOf((*MockStore)(nil).ConsumeOrganizationInvitation), ctx, arg)
}

// ConsumeVerificationToken mocks base method.
func (m *MockStore) ConsumeVerificationToken(ctx context.Context, arg sqlcgen.ConsumeVerificationTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeVerificationToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeVerificationToken indicates an expected call of ConsumeVerificationToken.
func (mr *MockStoreMockRecorder) ConsumeVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeVerificationToken", reflect.TypeOf((*MockStore)(nil).ConsumeVerificationToken), ctx, arg)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), ctx)
}

// DisableTwoFactor mocks base method.
func (m *MockStore) DisableTwoFactor(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTwoFactor", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTwoFactor indicates an expected call of DisableTwoFactor.
func (mr *MockStoreMockRecorder) DisableTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTwoFactor", reflect.TypeOf((*MockStore)(nil).DisableTwoFactor), ctx, userID)
}

// FindOrganizationByIDForUser mocks base method.
func (m *MockStore) FindOrganizationByIDForUser(ctx context.Context, arg sqlcgen.FindOrganizationByIDForUserParams) (sqlcgen.FindOrganizationByIDForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganizationByIDForUser", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindOrganizationByIDForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrganizationByIDForUser indicates an expected call of FindOrganizationByIDForUser.
func (mr *MockStoreMockRecorder) FindOrganizationByIDForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganizationByIDForUser", reflect.TypeOf((*MockStore)(nil).FindOrganizationByIDForUser), ctx, arg)
}

// FindOrganizationBySlugForUser mocks base method.
func (m *MockStore) FindOrganizationBySlugForUser(ctx context.Context, arg sqlcgen.FindOrganizationBySlugForUserParams) (sqlcgen.FindOrganizationBySlugForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganizationBySlugForUser", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindOrganizationBySlugForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrganizationBySlugForUser indicates an expected call of FindOrganizationBySlugForUser.
func (mr *MockStoreMockRecorder) FindOrganizationBySlugForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganizationBySlugForUser", reflect.TypeOf((*MockStore)(nil).FindOrganizationBySlugForUser), ctx, arg)
}

// FindOrganizationInvitationByToken mocks base method.
func (m *MockStore) FindOrganizationInvitationByToken(ctx context.Context, tokenHash string) (sqlcgen.FindOrganizationInvitationByTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganizationInvitationByToken", ctx, tokenHash)
	ret0, _ := ret[0].(sqlcgen.FindOrganizationInvitationByTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrganizationInvitationByToken indicates an expected call of FindOrganizationInvitationByToken.
func (mr *MockStoreMockRecorder) FindOrganizationInvitationByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganizationInvitationByToken", reflect.TypeOf((*MockStore)(nil).FindOrganizationInvitationByToken), ctx, tokenHash)
}

// FindPasswordAccountByUserID mocks base method.
func (m *MockStore) FindPasswordAccountByUserID(ctx context.Context, userID uuid.UUID) (sqlcgen.FindPasswordAccountByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordAccountByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.FindPasswordAccountByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPasswordAccountByUserID indicates an expected call of FindPasswordAccountByUserID.
func (mr *MockStoreMockRecorder) FindPasswordAccountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordAccountByUserID", reflect.TypeOf((*MockStore)(nil).FindPasswordAccountByUserID), ctx, userID)
}

// FindPendingOrganizationInvitationByEmail mocks base method.
func (m *MockStore) FindPendingOrganizationInvitationByEmail(ctx context.Context, arg sqlcgen.FindPendingOrganizationInvitationByEmailParams) (sqlcgen.FindPendingOrganizationInvitationByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingOrganizationInvitationByEmail", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindPendingOrganizationInvitationByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingOrganizationInvitationByEmail indicates an expected call of FindPendingOrganizationInvitationByEmail.
func (mr *MockStoreMockRecorder) FindPendingOrganizationInvitationByEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingOrganizationInvitationByEmail", reflect.TypeOf((*MockStore)(nil).FindPendingOrganizationInvitationByEmail), ctx, arg)
}

// FindTwoFactorByUserID mocks base method.
func (m *MockStore) FindTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (sqlcgen.FindTwoFactorByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTwoFactorByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.FindTwoFactorByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTwoFactorByUserID indicates an expected call of FindTwoFactorByUserID.
func (mr *MockStoreMockRecorder) FindTwoFactorByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTwoFactorByUserID", reflect.TypeOf((*MockStore)(nil).FindTwoFactorByUserID), ctx, userID)
}

// FindUserByEmail mocks base method.
func (m *MockStore) FindUserByEmail(ctx context.Context, email string) (sqlcgen.FindUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlcgen.FindUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockStoreMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockStore)(nil).FindUserByEmail), ctx, email)
}

// FindUserByProviderAccount mocks base method.
func (m *MockStore) FindUserByProviderAccount(ctx context.Context, arg sqlcgen.FindUserByProviderAccountParams) (sqlcgen.FindUserByProviderAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByProviderAccount", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindUserByProviderAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByProviderAccount indicates an expected call of FindUserByProviderAccount.
func (mr *MockStoreMockRecorder) FindUserByProviderAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByProviderAccount", reflect.TypeOf((*MockStore)(nil).FindUserByProviderAccount), ctx, arg)
}

// FindVerificationToken mocks base method.
func (m *MockStore) FindVerificationToken(ctx context.Context, arg sqlcgen.FindVerificationTokenParams) (sqlcgen.FindVerificationTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVerificationToken", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindVerificationTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVerificationToken indicates an expected call of FindVerificationToken.
func (mr *MockStoreMockRecorder) FindVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVerificationToken", reflect.TypeOf((*MockStore)(nil).FindVerificationToken), ctx, arg)
}

// GetInstanceName mocks base method.
func (m *MockStore) GetInstanceName(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceName", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceName indicates an expected call of GetInstanceName.
func (mr *MockStoreMockRecorder) GetInstanceName(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceName", reflect.TypeOf((*MockStore)(nil).GetInstanceName), ctx)
}

// GetActiveSessionTokenHashesForOrganization mocks base method.
func (m *MockStore) GetActiveSessionTokenHashesForOrganization(ctx context.Context, activeOrganizationID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionTokenHashesForOrganization", ctx, activeOrganizationID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSessionTokenHashesForOrganization indicates an expected call of GetActiveSessionTokenHashesForOrganization.
func (mr *MockStoreMockRecorder) GetActiveSessionTokenHashesForOrganization(ctx, activeOrganizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionTokenHashesForOrganization", reflect.TypeOf((*MockStore)(nil).GetActiveSessionTokenHashesForOrganization), ctx, activeOrganizationID)
}

// GetActiveSessionTokenHashesForUser mocks base method.
func (m *MockStore) GetActiveSessionTokenHashesForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSessionTokenHashesForUser", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSessionTokenHashesForUser indicates an expected call of GetActiveSessionTokenHashesForUser.
func (mr *MockStoreMockRecorder) GetActiveSessionTokenHashesForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSessionTokenHashesForUser", reflect.TypeOf((*MockStore)(nil).GetActiveSessionTokenHashesForUser), ctx, userID)
}

// GetSessionByTokenHash mocks base method.
func (m *MockStore) GetSessionByTokenHash(ctx context.Context, tokenHash string) (sqlcgen.GetSessionByTokenHashRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(sqlcgen.GetSessionByTokenHashRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByTokenHash indicates an expected call of GetSessionByTokenHash.
func (mr *MockStoreMockRecorder) GetSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).GetSessionByTokenHash), ctx, tokenHash)
}

// InsertAccount mocks base method.
func (m *MockStore) InsertAccount(ctx context.Context, arg sqlcgen.InsertAccountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccount", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAccount indicates an expected call of InsertAccount.
func (mr *MockStoreMockRecorder) InsertAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccount", reflect.TypeOf((*MockStore)(nil).InsertAccount), ctx, arg)
}

// InsertOrReplaceTwoFactor mocks base method.
func (m *MockStore) InsertOrReplaceTwoFactor(ctx context.Context, arg sqlcgen.InsertOrReplaceTwoFactorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrReplaceTwoFactor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrReplaceTwoFactor indicates an expected call of InsertOrReplaceTwoFactor.
func (mr *MockStoreMockRecorder) InsertOrReplaceTwoFactor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrReplaceTwoFactor", reflect.TypeOf((*MockStore)(nil).InsertOrReplaceTwoFactor), ctx, arg)
}

// InsertOrganization mocks base method.
func (m *MockStore) InsertOrganization(ctx context.Context, arg sqlcgen.InsertOrganizationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganization", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrganization indicates an expected call of InsertOrganization.
func (mr *MockStoreMockRecorder) InsertOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganization", reflect.TypeOf((*MockStore)(nil).InsertOrganization), ctx, arg)
}

// InsertOrganizationInvitation mocks base method.
func (m *MockStore) InsertOrganizationInvitation(ctx context.Context, arg sqlcgen.InsertOrganizationInvitationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganizationInvitation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrganizationInvitation indicates an expected call of InsertOrganizationInvitation.
func (mr *MockStoreMockRecorder) InsertOrganizationInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganizationInvitation", reflect.TypeOf((*MockStore)(nil).InsertOrganizationInvitation), ctx, arg)
}

// InsertOrganizationMember mocks base method.
func (m *MockStore) InsertOrganizationMember(ctx context.Context, arg sqlcgen.InsertOrganizationMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganizationMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrganizationMember indicates an expected call of InsertOrganizationMember.
func (mr *MockStoreMockRecorder) InsertOrganizationMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganizationMember", reflect.TypeOf((*MockStore)(nil).InsertOrganizationMember), ctx, arg)
}

// InsertOrganizationRole mocks base method.
func (m *MockStore) InsertOrganizationRole(ctx context.Context, arg sqlcgen.InsertOrganizationRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganizationRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrganizationRole indicates an expected call of InsertOrganizationRole.
func (mr *MockStoreMockRecorder) InsertOrganizationRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganizationRole", reflect.TypeOf((*MockStore)(nil).InsertOrganizationRole), ctx, arg)
}

// InsertOrganizationRolePermission mocks base method.
func (m *MockStore) InsertOrganizationRolePermission(ctx context.Context, arg sqlcgen.InsertOrganizationRolePermissionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganizationRolePermission", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOrganizationRolePermission indicates an expected call of InsertOrganizationRolePermission.
func (mr *MockStoreMockRecorder) InsertOrganizationRolePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganizationRolePermission", reflect.TypeOf((*MockStore)(nil).InsertOrganizationRolePermission), ctx, arg)
}

// InsertSession mocks base method.
func (m *MockStore) InsertSession(ctx context.Context, arg sqlcgen.InsertSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockStoreMockRecorder) InsertSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockStore)(nil).InsertSession), ctx, arg)
}

// InsertUser mocks base method.
func (m *MockStore) InsertUser(ctx context.Context, arg sqlcgen.InsertUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockStoreMockRecorder) InsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockStore)(nil).InsertUser), ctx, arg)
}

// InsertVerificationToken mocks base method.
func (m *MockStore) InsertVerificationToken(ctx context.Context, arg sqlcgen.InsertVerificationTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVerificationToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVerificationToken indicates an expected call of InsertVerificationToken.
func (mr *MockStoreMockRecorder) InsertVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVerificationToken", reflect.TypeOf((*MockStore)(nil).InsertVerificationToken), ctx, arg)
}

// ListOrganizationsForUser mocks base method.
func (m *MockStore) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]sqlcgen.ListOrganizationsForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationsForUser", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.ListOrganizationsForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationsForUser indicates an expected call of ListOrganizationsForUser.
func (mr *MockStoreMockRecorder) ListOrganizationsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsForUser", reflect.TypeOf((*MockStore)(nil).ListOrganizationsForUser), ctx, userID)
}

// MarkTwoFactorUsed mocks base method.
func (m *MockStore) MarkTwoFactorUsed(ctx context.Context, arg sqlcgen.MarkTwoFactorUsedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTwoFactorUsed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTwoFactorUsed indicates an expected call of MarkTwoFactorUsed.
func (mr *MockStoreMockRecorder) MarkTwoFactorUsed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTwoFactorUsed", reflect.TypeOf((*MockStore)(nil).MarkTwoFactorUsed), ctx, arg)
}

// RegisterTwoFactorFailure mocks base method.
func (m *MockStore) RegisterTwoFactorFailure(ctx context.Context, arg sqlcgen.RegisterTwoFactorFailureParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTwoFactorFailure", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterTwoFactorFailure indicates an expected call of RegisterTwoFactorFailure.
func (mr *MockStoreMockRecorder) RegisterTwoFactorFailure(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTwoFactorFailure", reflect.TypeOf((*MockStore)(nil).RegisterTwoFactorFailure), ctx, arg)
}

// RevokeSessionByTokenHash mocks base method.
func (m *MockStore) RevokeSessionByTokenHash(ctx context.Context, arg sqlcgen.RevokeSessionByTokenHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByTokenHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionByTokenHash indicates an expected call of RevokeSessionByTokenHash.
func (mr *MockStoreMockRecorder) RevokeSessionByTokenHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).RevokeSessionByTokenHash), ctx, arg)
}

// RevokeSessionsForUser mocks base method.
func (m *MockStore) RevokeSessionsForUser(ctx context.Context, arg sqlcgen.RevokeSessionsForUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionsForUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSessionsForUser indicates an expected call of RevokeSessionsForUser.
func (mr *MockStoreMockRecorder) RevokeSessionsForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionsForUser", reflect.TypeOf((*MockStore)(nil).RevokeSessionsForUser), ctx, arg)
}

// UpdateUserEmailVerifiedAt mocks base method.
func (m *MockStore) UpdateUserEmailVerifiedAt(ctx context.Context, arg sqlcgen.UpdateUserEmailVerifiedAtParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmailVerifiedAt", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmailVerifiedAt indicates an expected call of UpdateUserEmailVerifiedAt.
func (mr *MockStoreMockRecorder) UpdateUserEmailVerifiedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmailVerifiedAt", reflect.TypeOf((*MockStore)(nil).UpdateUserEmailVerifiedAt), ctx, arg)
}

// UpdateUserPasswordHash mocks base method.
func (m *MockStore) UpdateUserPasswordHash(ctx context.Context, arg sqlcgen.UpdateUserPasswordHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordHash indicates an expected call of UpdateUserPasswordHash.
func (mr *MockStoreMockRecorder) UpdateUserPasswordHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordHash", reflect.TypeOf((*MockStore)(nil).UpdateUserPasswordHash), ctx, arg)
}
