// Code generated by hand. DO NOT EDIT.
package auth

import (
	"context"
	"reflect"

	"github.com/google/uuid"
	"go.uber.org/mock/gomock"

	"github.com/sidarth-23/dinchy/internal/platform/store/sqlcgen"
)

type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

type MockStoreMockRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock: mock}
	return mock
}

func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

func (m *MockStore) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), ctx)
}

func (m *MockStore) InsertUser(ctx context.Context, arg sqlcgen.InsertUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockStore)(nil).InsertUser), ctx, arg)
}

func (m *MockStore) InsertAccount(ctx context.Context, arg sqlcgen.InsertAccountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAccount", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAccount", reflect.TypeOf((*MockStore)(nil).InsertAccount), ctx, arg)
}

func (m *MockStore) InsertOrganisation(ctx context.Context, arg sqlcgen.InsertOrganisationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganisation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertOrganisation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganisation", reflect.TypeOf((*MockStore)(nil).InsertOrganisation), ctx, arg)
}

func (m *MockStore) InsertOrganisationMember(ctx context.Context, arg sqlcgen.InsertOrganisationMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganisationMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertOrganisationMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganisationMember", reflect.TypeOf((*MockStore)(nil).InsertOrganisationMember), ctx, arg)
}

func (m *MockStore) FindUserByEmail(ctx context.Context, email string) (sqlcgen.FindUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlcgen.FindUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockStore)(nil).FindUserByEmail), ctx, email)
}

func (m *MockStore) UpdateUserEmailVerifiedAt(ctx context.Context, arg sqlcgen.UpdateUserEmailVerifiedAtParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmailVerifiedAt", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) UpdateUserEmailVerifiedAt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmailVerifiedAt", reflect.TypeOf((*MockStore)(nil).UpdateUserEmailVerifiedAt), ctx, arg)
}

func (m *MockStore) FindPasswordAccountByUserID(ctx context.Context, userID uuid.UUID) (sqlcgen.FindPasswordAccountByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPasswordAccountByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.FindPasswordAccountByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindPasswordAccountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPasswordAccountByUserID", reflect.TypeOf((*MockStore)(nil).FindPasswordAccountByUserID), ctx, userID)
}

func (m *MockStore) FindUserByProviderAccount(ctx context.Context, arg sqlcgen.FindUserByProviderAccountParams) (sqlcgen.FindUserByProviderAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByProviderAccount", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindUserByProviderAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindUserByProviderAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByProviderAccount", reflect.TypeOf((*MockStore)(nil).FindUserByProviderAccount), ctx, arg)
}

func (m *MockStore) ListOrganisationsForUser(ctx context.Context, userID uuid.UUID) ([]sqlcgen.ListOrganisationsForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganisationsForUser", ctx, userID)
	ret0, _ := ret[0].([]sqlcgen.ListOrganisationsForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) ListOrganisationsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganisationsForUser", reflect.TypeOf((*MockStore)(nil).ListOrganisationsForUser), ctx, userID)
}

func (m *MockStore) FindOrganisationBySlugForUser(ctx context.Context, arg sqlcgen.FindOrganisationBySlugForUserParams) (sqlcgen.FindOrganisationBySlugForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganisationBySlugForUser", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindOrganisationBySlugForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindOrganisationBySlugForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganisationBySlugForUser", reflect.TypeOf((*MockStore)(nil).FindOrganisationBySlugForUser), ctx, arg)
}

func (m *MockStore) FindOrganisationByIDForUser(ctx context.Context, arg sqlcgen.FindOrganisationByIDForUserParams) (sqlcgen.FindOrganisationByIDForUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganisationByIDForUser", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindOrganisationByIDForUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindOrganisationByIDForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganisationByIDForUser", reflect.TypeOf((*MockStore)(nil).FindOrganisationByIDForUser), ctx, arg)
}

func (m *MockStore) UpdateUserPasswordHash(ctx context.Context, arg sqlcgen.UpdateUserPasswordHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) UpdateUserPasswordHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordHash", reflect.TypeOf((*MockStore)(nil).UpdateUserPasswordHash), ctx, arg)
}

func (m *MockStore) InsertVerificationToken(ctx context.Context, arg sqlcgen.InsertVerificationTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVerificationToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVerificationToken", reflect.TypeOf((*MockStore)(nil).InsertVerificationToken), ctx, arg)
}

func (m *MockStore) FindVerificationToken(ctx context.Context, arg sqlcgen.FindVerificationTokenParams) (sqlcgen.FindVerificationTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVerificationToken", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindVerificationTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVerificationToken", reflect.TypeOf((*MockStore)(nil).FindVerificationToken), ctx, arg)
}

func (m *MockStore) ConsumeVerificationToken(ctx context.Context, arg sqlcgen.ConsumeVerificationTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeVerificationToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) ConsumeVerificationToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeVerificationToken", reflect.TypeOf((*MockStore)(nil).ConsumeVerificationToken), ctx, arg)
}

func (m *MockStore) InsertOrganisationInvitation(ctx context.Context, arg sqlcgen.InsertOrganisationInvitationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrganisationInvitation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertOrganisationInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrganisationInvitation", reflect.TypeOf((*MockStore)(nil).InsertOrganisationInvitation), ctx, arg)
}

func (m *MockStore) FindOrganisationInvitationByToken(ctx context.Context, tokenHash string) (sqlcgen.FindOrganisationInvitationByTokenRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrganisationInvitationByToken", ctx, tokenHash)
	ret0, _ := ret[0].(sqlcgen.FindOrganisationInvitationByTokenRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindOrganisationInvitationByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrganisationInvitationByToken", reflect.TypeOf((*MockStore)(nil).FindOrganisationInvitationByToken), ctx, tokenHash)
}

func (m *MockStore) FindPendingOrganisationInvitationByEmail(ctx context.Context, arg sqlcgen.FindPendingOrganisationInvitationByEmailParams) (sqlcgen.FindPendingOrganisationInvitationByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingOrganisationInvitationByEmail", ctx, arg)
	ret0, _ := ret[0].(sqlcgen.FindPendingOrganisationInvitationByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindPendingOrganisationInvitationByEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingOrganisationInvitationByEmail", reflect.TypeOf((*MockStore)(nil).FindPendingOrganisationInvitationByEmail), ctx, arg)
}

func (m *MockStore) ConsumeOrganisationInvitation(ctx context.Context, arg sqlcgen.ConsumeOrganisationInvitationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeOrganisationInvitation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) ConsumeOrganisationInvitation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeOrganisationInvitation", reflect.TypeOf((*MockStore)(nil).ConsumeOrganisationInvitation), ctx, arg)
}

func (m *MockStore) InsertOrReplaceTwoFactor(ctx context.Context, arg sqlcgen.InsertOrReplaceTwoFactorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrReplaceTwoFactor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertOrReplaceTwoFactor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrReplaceTwoFactor", reflect.TypeOf((*MockStore)(nil).InsertOrReplaceTwoFactor), ctx, arg)
}

func (m *MockStore) FindTwoFactorByUserID(ctx context.Context, userID uuid.UUID) (sqlcgen.FindTwoFactorByUserIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTwoFactorByUserID", ctx, userID)
	ret0, _ := ret[0].(sqlcgen.FindTwoFactorByUserIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) FindTwoFactorByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTwoFactorByUserID", reflect.TypeOf((*MockStore)(nil).FindTwoFactorByUserID), ctx, userID)
}

func (m *MockStore) ConfirmTwoFactor(ctx context.Context, arg sqlcgen.ConfirmTwoFactorParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmTwoFactor", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) ConfirmTwoFactor(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmTwoFactor", reflect.TypeOf((*MockStore)(nil).ConfirmTwoFactor), ctx, arg)
}

func (m *MockStore) MarkTwoFactorUsed(ctx context.Context, arg sqlcgen.MarkTwoFactorUsedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTwoFactorUsed", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) MarkTwoFactorUsed(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTwoFactorUsed", reflect.TypeOf((*MockStore)(nil).MarkTwoFactorUsed), ctx, arg)
}

func (m *MockStore) RegisterTwoFactorFailure(ctx context.Context, arg sqlcgen.RegisterTwoFactorFailureParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTwoFactorFailure", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) RegisterTwoFactorFailure(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTwoFactorFailure", reflect.TypeOf((*MockStore)(nil).RegisterTwoFactorFailure), ctx, arg)
}

func (m *MockStore) DisableTwoFactor(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTwoFactor", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) DisableTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTwoFactor", reflect.TypeOf((*MockStore)(nil).DisableTwoFactor), ctx, userID)
}

func (m *MockStore) ListSSOProviderSettings(ctx context.Context) ([]sqlcgen.SsoProviderSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSSOProviderSettings", ctx)
	ret0, _ := ret[0].([]sqlcgen.SsoProviderSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) ListSSOProviderSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSSOProviderSettings", reflect.TypeOf((*MockStore)(nil).ListSSOProviderSettings), ctx)
}

func (m *MockStore) UpsertSSOProviderSetting(ctx context.Context, arg sqlcgen.UpsertSSOProviderSettingParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSSOProviderSetting", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) UpsertSSOProviderSetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSSOProviderSetting", reflect.TypeOf((*MockStore)(nil).UpsertSSOProviderSetting), ctx, arg)
}

func (m *MockStore) InsertSession(ctx context.Context, arg sqlcgen.InsertSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) InsertSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockStore)(nil).InsertSession), ctx, arg)
}

func (m *MockStore) GetSessionByTokenHash(ctx context.Context, tokenHash string) (sqlcgen.GetSessionByTokenHashRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(sqlcgen.GetSessionByTokenHashRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) GetSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).GetSessionByTokenHash), ctx, tokenHash)
}

func (m *MockStore) RevokeSessionByTokenHash(ctx context.Context, arg sqlcgen.RevokeSessionByTokenHashParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionByTokenHash", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) RevokeSessionByTokenHash(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionByTokenHash", reflect.TypeOf((*MockStore)(nil).RevokeSessionByTokenHash), ctx, arg)
}

func (m *MockStore) RevokeSessionsForUser(ctx context.Context, arg sqlcgen.RevokeSessionsForUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSessionsForUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockStoreMockRecorder) RevokeSessionsForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSessionsForUser", reflect.TypeOf((*MockStore)(nil).RevokeSessionsForUser), ctx, arg)
}

func (m *MockStore) GetInstanceName(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceName", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockStoreMockRecorder) GetInstanceName(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceName", reflect.TypeOf((*MockStore)(nil).GetInstanceName), ctx)
}
