// Code generated by cmd/codegen permission; DO NOT EDIT.

package permission

import "github.com/sidarth-23/dinchy/internal/foundation/i18n"

type Role string
type RoleDefinition struct {
	Role        Role
	Description string
	MessageCode i18n.Code
	Permissions []Permission
}

const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
)

var roles = map[Role]RoleDefinition{
	RoleAdmin:  {Role: RoleAdmin, Description: "Organization administrator", MessageCode: i18n.Code("account.access.roles.admin"), Permissions: []Permission{AuditLogsRead, AuthInvitationsCreate, AuthRolesManage}},
	RoleMember: {Role: RoleMember, Description: "Organization member", MessageCode: i18n.Code("account.access.roles.member"), Permissions: []Permission{}},
}

func BuiltInRoles() []Role { return []Role{RoleAdmin, RoleMember} }
func DefaultRolePermissions(role Role) []Permission {
	return append([]Permission(nil), roles[role].Permissions...)
}
