// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Account struct {
	ID                string
	UserID            string
	Provider          string
	ProviderAccountID string
	PasswordHash      sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type AppSetting struct {
	ID                            string
	InstanceName                  string
	SessionIdleTimeoutSeconds     int64
	SessionMaxLifetimeSeconds     int64
	SessionCleanupIntervalSeconds int64
	SessionRetentionSeconds       int64
	CreatedAt                     string
	UpdatedAt                     string
}

type AuthAuditLog struct {
	ID           string
	EventType    string
	UserID       sql.NullString
	ActorUserID  sql.NullString
	IpAddress    string
	UserAgent    string
	MetadataJson string
	CreatedAt    string
}

type Organisation struct {
	ID        string
	Name      string
	Slug      string
	Logo      sql.NullString
	CreatedAt string
	UpdatedAt string
}

type OrganisationInvitation struct {
	ID              string
	OrganisationID  string
	Email           string
	Role            string
	Status          string
	TokenHash       string
	ExpiresAt       string
	InvitedByUserID string
	AcceptedAt      sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

type OrganisationMember struct {
	ID             string
	OrganisationID string
	UserID         string
	Role           string
	CreatedAt      string
	UpdatedAt      string
}

type ScheduledTask struct {
	ID                      string
	TaskName                string
	Enabled                 int64
	ScheduleIntervalSeconds int64
	LeaseOwner              sql.NullString
	LeaseExpiresAt          sql.NullString
	LastRunAt               sql.NullString
	LastFinishedAt          sql.NullString
	NextRunAt               sql.NullString
	LastStatus              sql.NullString
	LastErrorCode           sql.NullString
	LastErrorMessage        sql.NullString
	UpdatedAt               string
}

type Session struct {
	ID                   string
	UserID               string
	ActiveOrganisationID string
	TokenHash            string
	IpAddress            string
	UserAgent            string
	LastSeenAt           string
	IdleExpiresAt        string
	ExpiresAt            string
	RevokedAt            sql.NullString
	CreatedAt            string
	UpdatedAt            string
}

type SsoProviderSetting struct {
	ProviderID   string
	ClientID     sql.NullString
	ClientSecret sql.NullString
	CallbackUrl  sql.NullString
	Enabled      int64
	CreatedAt    string
	UpdatedAt    string
}

type TwoFactor struct {
	ID                      string
	UserID                  string
	Secret                  string
	Verified                int64
	LastUsedStep            sql.NullInt64
	FailedVerificationCount int64
	LockedUntil             sql.NullString
	CreatedAt               string
	UpdatedAt               string
}

type User struct {
	ID              string
	Email           string
	DisplayName     string
	EmailVerifiedAt sql.NullString
	DisabledAt      sql.NullString
	LastLoginAt     sql.NullString
	CreatedAt       string
	UpdatedAt       string
}

type VerificationToken struct {
	ID         string
	UserID     sql.NullString
	Email      string
	Purpose    string
	TokenHash  string
	ExpiresAt  string
	ConsumedAt sql.NullString
	CreatedAt  string
	UpdatedAt  string
}
