// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AppSetting struct {
	ID                            string
	InstanceName                  string
	SessionIdleTimeoutSeconds     int64
	SessionMaxLifetimeSeconds     int64
	SessionCleanupIntervalSeconds int64
	SessionRetentionSeconds       int64
	CreatedAt                     string
	UpdatedAt                     string
}

type AuthAuditLog struct {
	ID           string
	EventType    string
	UserID       sql.NullString
	ActorUserID  sql.NullString
	IpAddress    string
	UserAgent    string
	MetadataJson string
	CreatedAt    string
}

type ScheduledTask struct {
	ID                      string
	TaskName                string
	Enabled                 int64
	ScheduleIntervalSeconds int64
	LeaseOwner              sql.NullString
	LeaseExpiresAt          sql.NullString
	LastRunAt               sql.NullString
	LastFinishedAt          sql.NullString
	NextRunAt               sql.NullString
	LastStatus              sql.NullString
	LastErrorCode           sql.NullString
	LastErrorMessage        sql.NullString
	UpdatedAt               string
}

type Session struct {
	ID            string
	UserID        string
	TokenHash     string
	IpAddress     string
	UserAgent     string
	LastSeenAt    string
	IdleExpiresAt string
	ExpiresAt     string
	RevokedAt     sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	DisabledAt   sql.NullString
	LastLoginAt  sql.NullString
	CreatedAt    string
	UpdatedAt    string
}
