// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteEndedSessionsOlderThan = `-- name: DeleteEndedSessionsOlderThan :execresult
DELETE FROM sessions
WHERE (revoked_at IS NOT NULL OR expires_at < ?) AND updated_at < ?
`

type DeleteEndedSessionsOlderThanParams struct {
	ExpiresAt string
	UpdatedAt string
}

func (q *Queries) DeleteEndedSessionsOlderThan(ctx context.Context, arg DeleteEndedSessionsOlderThanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteEndedSessionsOlderThan, arg.ExpiresAt, arg.UpdatedAt)
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, u.email, u.display_name, u.role, s.idle_expires_at, s.expires_at, s.revoked_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type GetSessionByTokenHashRow struct {
	ID            string
	UserID        string
	Email         string
	DisplayName   string
	Role          string
	IdleExpiresAt string
	ExpiresAt     string
	RevokedAt     sql.NullString
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, user_id, token_hash, ip_address, user_agent, last_seen_at, idle_expires_at, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID            string
	UserID        string
	TokenHash     string
	IpAddress     string
	UserAgent     string
	LastSeenAt    string
	IdleExpiresAt string
	ExpiresAt     string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = ?, updated_at = ?
WHERE token_hash = ? AND revoked_at IS NULL
`

type RevokeSessionByTokenHashParams struct {
	RevokedAt sql.NullString
	UpdatedAt string
	TokenHash string
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, arg.RevokedAt, arg.UpdatedAt, arg.TokenHash)
	return err
}
