// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sso_settings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const listSSOProviderSettings = `-- name: ListSSOProviderSettings :many
SELECT provider_id, client_id, client_secret, callback_url, enabled, created_at, updated_at
FROM sso_provider_settings
ORDER BY provider_id
`

func (q *Queries) ListSSOProviderSettings(ctx context.Context) ([]SsoProviderSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSSOProviderSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoProviderSetting{}
	for rows.Next() {
		var i SsoProviderSetting
		if err := rows.Scan(
			&i.ProviderID,
			&i.ClientID,
			&i.ClientSecret,
			&i.CallbackUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSSOProviderSetting = `-- name: UpsertSSOProviderSetting :exec
INSERT INTO sso_provider_settings (
    provider_id,
    client_id,
    client_secret,
    callback_url,
    enabled,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(provider_id) DO UPDATE SET
    client_id = excluded.client_id,
    client_secret = excluded.client_secret,
    callback_url = excluded.callback_url,
    enabled = excluded.enabled,
    updated_at = excluded.updated_at
`

type UpsertSSOProviderSettingParams struct {
	ProviderID   string
	ClientID     sql.NullString
	ClientSecret sql.NullString
	CallbackUrl  sql.NullString
	Enabled      int64
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) UpsertSSOProviderSetting(ctx context.Context, arg UpsertSSOProviderSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSSOProviderSetting,
		arg.ProviderID,
		arg.ClientID,
		arg.ClientSecret,
		arg.CallbackUrl,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
