// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimTask = `-- name: ClaimTask :execresult
UPDATE scheduled_tasks
SET lease_owner = ?, lease_expires_at = ?, last_run_at = ?, updated_at = ?
WHERE task_name = ?
  AND enabled = 1
  AND (lease_expires_at IS NULL OR lease_expires_at < ?)
  AND (next_run_at IS NULL OR next_run_at <= ?)
`

type ClaimTaskParams struct {
	LeaseOwner       sql.NullString
	LeaseExpiresAt   sql.NullString
	LastRunAt        sql.NullString
	UpdatedAt        string
	TaskName         string
	LeaseExpiresAt_2 sql.NullString
	NextRunAt        sql.NullString
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimTask,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.LastRunAt,
		arg.UpdatedAt,
		arg.TaskName,
		arg.LeaseExpiresAt_2,
		arg.NextRunAt,
	)
}

const ensureTask = `-- name: EnsureTask :exec
INSERT INTO scheduled_tasks (id, task_name, enabled, schedule_interval_seconds, next_run_at, updated_at)
VALUES (?, ?, 1, ?, ?, ?)
ON CONFLICT(task_name) DO NOTHING
`

type EnsureTaskParams struct {
	ID                      string
	TaskName                string
	ScheduleIntervalSeconds int64
	NextRunAt               sql.NullString
	UpdatedAt               string
}

func (q *Queries) EnsureTask(ctx context.Context, arg EnsureTaskParams) error {
	_, err := q.db.ExecContext(ctx, ensureTask,
		arg.ID,
		arg.TaskName,
		arg.ScheduleIntervalSeconds,
		arg.NextRunAt,
		arg.UpdatedAt,
	)
	return err
}

const finishTask = `-- name: FinishTask :exec
UPDATE scheduled_tasks
SET
    lease_owner       = NULL,
    lease_expires_at  = NULL,
    last_finished_at  = ?,
    next_run_at       = ?,
    last_status       = ?,
    last_error_code   = ?,
    last_error_message = ?,
    updated_at        = ?
WHERE task_name = ?
`

type FinishTaskParams struct {
	LastFinishedAt   sql.NullString
	NextRunAt        sql.NullString
	LastStatus       sql.NullString
	LastErrorCode    sql.NullString
	LastErrorMessage sql.NullString
	UpdatedAt        string
	TaskName         string
}

func (q *Queries) FinishTask(ctx context.Context, arg FinishTaskParams) error {
	_, err := q.db.ExecContext(ctx, finishTask,
		arg.LastFinishedAt,
		arg.NextRunAt,
		arg.LastStatus,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.UpdatedAt,
		arg.TaskName,
	)
	return err
}
