// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sidarth-23/dinchy/internal/domain (interfaces: SettingsReader)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mock_settings_reader_test.go -package=domain github.com/sidarth-23/dinchy/internal/domain SettingsReader
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsReader is a mock of SettingsReader interface.
type MockSettingsReader struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsReaderMockRecorder
	isgomock struct{}
}

// MockSettingsReaderMockRecorder is the mock recorder for MockSettingsReader.
type MockSettingsReaderMockRecorder struct {
	mock *MockSettingsReader
}

// NewMockSettingsReader creates a new mock instance.
func NewMockSettingsReader(ctrl *gomock.Controller) *MockSettingsReader {
	mock := &MockSettingsReader{ctrl: ctrl}
	mock.recorder = &MockSettingsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsReader) EXPECT() *MockSettingsReaderMockRecorder {
	return m.recorder
}

// Bootstrap mocks base method.
func (m *MockSettingsReader) Bootstrap(ctx context.Context) (BootstrapState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bootstrap", ctx)
	ret0, _ := ret[0].(BootstrapState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockSettingsReaderMockRecorder) Bootstrap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bootstrap", reflect.TypeOf((*MockSettingsReader)(nil).Bootstrap), ctx)
}
